FileVersion = 1

[Project]
Name = "Sedulous.Model.FBX"
TargetType = "BeefLib"
StartupObject = "Sedulous.Model.FBX.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Model" = "*"
"Sedulous.Model.IO" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"ufbx-Beef" = "*"
