FileVersion = 1

[Project]
Name = "Sample012_Wireframe"
StartupObject = "Sample012_Wireframe.Program"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.RHI.DX12" = "*"
"Sedulous.RHI.Vulkan" = "*"
GraphicsFramework = "*"
