FileVersion = 1

[Project]
Name = "Samples.HelloWindow"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.HelloWindow.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
