FileVersion = 1

[Project]
Name = "TowerDefense.App"
StartupObject = "TowerDefense.Program"

[Dependencies]
corlib = "*"
"TowerDefense.Core" = "*"
"Sedulous.Platform.SDL3" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
