FileVersion = 1

[Project]
Name = "Sedulous.Engine.Animation.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Animation.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Core" = "*"
"Sedulous.PropertyAnimation" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Engine.Render" = "*"
