FileVersion = 1

[Project]
Name = "FontRendering"
StartupObject = "FontRendering.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Images" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.IO" = "*"
"Sedulous.Fonts.TTF" = "*"
