FileVersion = 1

[Project]
Name = "Sedulous.Fonts.TrueType.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Fonts.TrueType.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TrueType" = "*"
