FileVersion = 1

[Project]
Name = "Samples.RHI.Smoketest"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.RHI.Smoketest.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Samples.Framework" = "*"
