FileVersion = 1

[Project]
Name = "Sedulous.Editor.Heightfield.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Heightfield.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Editor.Heightfield" = "*"
