FileVersion = 1

[Project]
Name = "Sedulous.Vegetation.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Vegetation.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Vegetation.Resource" = "*"
"Sedulous.VFS" = "*"
