FileVersion = 1

[Project]
Name = "Sedulous.Integration.Composition"
TargetType = "BeefTest"
StartupObject = "Sedulous.Integration.Composition.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Engine.Composition" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Registration" = "*"
"Sedulous.Resource" = "*"
