FileVersion = 1

[Project]
Name = "Sedulous.Engine.Scene.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Scene.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Engine.Scene" = "*"
