FileVersion = 1

[Project]
Name = "Sedulous.Engine.GameInstance"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.GameInstance.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Input" = "*"
"Sedulous.Messaging" = "*"
"Sedulous.Net.Manager" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Engine.Net" = "*"
"Sedulous.Engine.Script" = "*"
"Sedulous.Engine.Script.Facades" = "*"
"Sedulous.Script" = "*"
"Sedulous.Script.Resource" = "*"
