FileVersion = 1

[Project]
Name = "Sedulous.Editor.GameUI"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.GameUI.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Xml" = "*"
"Sedulous.Content" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.UI.Pipeline" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.UI.Viewport" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
