FileVersion = 1

[Project]
Name = "Sedulous.UI.Viewport.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI.Viewport.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.Null" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Viewport" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
