FileVersion = 1

[Project]
Name = "Sedulous.Shaders.System.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Shaders.System.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.VFS" = "*"
"Dxc-Beef" = "*"
