FileVersion = 1

[Project]
Name = "Sedulous.UI.VFS"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI.VFS.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.UI" = "*"
"Sedulous.VFS" = "*"
