FileVersion = 1

[Project]
Name = "EngineRenderStressTest"
StartupObject = "EngineRenderStressTest.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.App" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Renderer" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resources" = "*"
"Sedulous.Geometry.Tooling" = "*"
"Sedulous.Geometry.Tooling.Resources" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Images.Loading" = "*"
"Sedulous.Images.STB" = "*"
"Sedulous.Images.SDL" = "*"
"Sedulous.Textures.Resources" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Profiler" = "*"
