FileVersion = 1

[Project]
Name = "Sedulous.RHI.Vulkan.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.RHI.Vulkan.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Bulkan" = "*"
