FileVersion = 1

[Project]
Name = "Sedulous.Materials.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Materials.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Pipeline" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.VFS" = "*"
