FileVersion = 1

[Project]
Name = "Sedulous.Heightfield.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Heightfield.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
