FileVersion = 1

[Project]
Name = "Sedulous.Scene.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Scene.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Messaging" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
