FileVersion = 1

[Project]
Name = "Sedulous.Editor.PropertyAnimation"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.PropertyAnimation.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Render" = "*"
"Sedulous.PropertyAnimation" = "*"
"Sedulous.PropertyAnimation.Resource" = "*"
"Sedulous.PropertyAnimation.Pipeline" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
