FileVersion = 1

[Project]
Name = "Sedulous.RHI.WebGPU"
TargetType = "BeefLib"
StartupObject = "Sedulous.RHI.WebGPU.Program"

[Dependencies]
corlib = "*"
"wgpu-Beef" = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
