FileVersion = 1

[Project]
Name = "RuntimeSampleFramework"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Platform" = "*"
"Sedulous.Platform.SDL3" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VFS.Disk" = "*"
"Sedulous.Jobs" = "*"
