FileVersion = 1

[Project]
Name = "Sedulous.Materials.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Materials.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.Resource" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.Materials" = "*"
