FileVersion = 1

[Project]
Name = "Sedulous.UI.Gamekit"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI.Gamekit.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Input" = "*"
"Sedulous.UI" = "*"
"Sedulous.VG" = "*"
