FileVersion = 1

[Project]
Name = "Sedulous.Terrain.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Terrain.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Heightfield.Resource" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Terrain.Pipeline" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.VFS" = "*"
