FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Coverage.Baker.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Fonts.Coverage.Baker.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Coverage" = "*"
"Sedulous.Fonts.Coverage.Baker" = "*"
"Sedulous.Fonts.TrueType" = "*"
