FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Fonts.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Image" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Coverage" = "*"
"Sedulous.Fonts.DistanceField" = "*"
"Sedulous.Fonts.TrueType" = "*"
