FileVersion = 1

[Project]
Name = "Sedulous.PropertyAnimation.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.PropertyAnimation.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.PropertyAnimation" = "*"
