FileVersion = 1

[Project]
Name = "Samples.RHI.Sample026_DynamicOffsets"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.RHI.Sample026_DynamicOffsets.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Samples.Framework" = "*"
