FileVersion = 1

[Project]
Name = "Sedulous.Engine.Core"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Platform" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Inspection" = "*"
"Sedulous.Profiler" = "*"
