FileVersion = 1

[Project]
Name = "Sedulous.Input.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Input.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Input" = "*"
"Sedulous.Input.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
