FileVersion = 1

[Project]
Name = "Samples.GameUiSandbox"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.GameUiSandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.Input" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Gamekit" = "*"
