FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI" = "*", "Sedulous.GUI" = "*", "Sedulous.VG.Renderer" = "*", "Sedulous.Shell" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Images" = "*", "Sedulous.VG" = "*"}

[Project]
Name = "Sedulous.GUI.Viewport"
