FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample001_Triangle"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample001_Triangle.Program"

[Dependencies]
corlib = "*"
