FileVersion = 1

[Project]
Name = "Sedulous.Script.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Script.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Script" = "*"
