FileVersion = 1

[Project]
Name = "Sedulous.Editor.Audio.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Audio.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Audio" = "*"
"Sedulous.Audio.Pipeline" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.Audio" = "*"
