FileVersion = 1

[Project]
Name = "Sedulous.Image.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Image.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Image.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.VFS" = "*"
