FileVersion = 1

[Project]
Name = "Sedulous.UI"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Image" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.SVG" = "*"
"Sedulous.Xml" = "*"
