FileVersion = 1

[Project]
Name = "Sedulous.UI"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.VG" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Images" = "*"
"Sedulous.VG.SVG" = "*"
"Sedulous.Xml" = "*"
