FileVersion = 1

[Project]
Name = "Sedulous.Image.IO.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Image.IO.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
