using System;
using wgpu_Beef;
using Sedulous.Core;
using Sedulous.RHI;

namespace Sedulous.RHI.WebGPU;

/// A texture, either created here or WRAPPED around one the surface owns.
class WebGpuTexture : ITexture
{
	private WGPUTexture mHandle;
	private TextureDesc mDesc;
	private ResourceState mInitialState = .Undefined;
	/// False for a wrapped swapchain image, which the surface frees.
	private bool mOwnsHandle = true;

	public TextureDesc Desc => mDesc;
	public WGPUTexture Handle => mHandle;

	public ResourceState InitialState
	{
		get => mInitialState;
		set => mInitialState = value;
	}

	public ~this()
	{
		if ((mHandle != null) && mOwnsHandle)
			wgpuTextureRelease(mHandle);

		mHandle = null;
	}

	public Result<void> Initialize(WGPUDevice device, TextureDesc desc)
	{
		mDesc = desc;

		let format = WebGpuConversions.ToWgpuTextureFormat(desc.Format);
		if ((format == .WGPUTextureFormat_Undefined) && (desc.Format != .Undefined))
			return .Err; // the format has no WebGPU equivalent

		WGPUTextureDescriptor wgpu = .();
		wgpu.label = WebGpuConversions.ToWgpuStringView(desc.Label);
		wgpu.usage = WebGpuConversions.ToWgpuTextureUsage(desc.Usage);

		// Mip chains are generated by the internal blit PASS, WebGPU having no image
		// blit, so every mip has to be renderable and samplable. Widened only for the 2D
		// colour formats that pass can actually target.
		if ((desc.MipLevelCount > 1) && (desc.Dimension == .Texture2D)
			&& WebGpuConversions.IsBlitCapableFormat(desc.Format))
			wgpu.usage |= WGPUTextureUsage_RenderAttachment | WGPUTextureUsage_TextureBinding;

		wgpu.dimension = WebGpuConversions.ToWgpuTextureDimension(desc.Dimension);
		wgpu.size.width = desc.Width;
		wgpu.size.height = desc.Height;
		// WebGPU folds array layers into the depth field; a 3D texture has no layers.
		wgpu.size.depthOrArrayLayers = (desc.Dimension == .Texture3D) ? desc.Depth
			: desc.ArrayLayerCount;
		wgpu.format = format;
		wgpu.mipLevelCount = desc.MipLevelCount;
		wgpu.sampleCount = desc.SampleCount;

		mHandle = wgpuDeviceCreateTexture(device, &wgpu);
		return (mHandle != null) ? .Ok : .Err;
	}

	/// Wraps an EXTERNALLY owned texture, which is the swapchain's current image. No
	/// release on destruction: the surface owns it and hands it back each frame.
	public void WrapExternal(WGPUTexture texture, TextureDesc desc)
	{
		mHandle = texture;
		mOwnsHandle = false;
		mDesc = desc;
	}
}
