using System;
using System.Collections;
using System.Reflection;
using Sedulous.Core;
using Sedulous.Core.Logging;
using Sedulous.Core.Serialization;
using Sedulous.Engine.Composition;
using Sedulous.Engine.Script;
using Sedulous.Json;
using Sedulous.Mcp;
using Sedulous.Pipeline.Core;
using Sedulous.Resource;
using Sedulous.Scene;
using Sedulous.Scene.Resource;
using Sedulous.Script.Resource;
using Sedulous.Xml.Serialization;

namespace Sedulous.Editor.Mcp;

/// The scene format reference an agent authors scenes from: two documents, generated by the
/// running host from its own registrations, so they cannot describe a different build.
///
/// - SceneExample.scene.xml: a real save of a scene composed in code: every registered
///   component at its defaults on an entity of its own, every settings block, a parent and
///   child, a script behaviour carrying one override of each property kind. Exactly what
///   scene_write accepts, because it is what the engine writes.
/// - SceneSchema.json: what each Serialize body wrote, recorded through the real write path
///   (SchemaRecorder): keys, kinds and defaults in wire order, the data version chain, joined
///   to reflection for enum names, attributes and reference targets.
///
/// Both are deterministic (seeded guids, composition order, no stamps). The hosts serve them
/// as docs://generated/* beside the shipping docs, and component_schema answers one entry.
class SceneReference
{
	public const String cExampleUri = "docs://generated/SceneExample.scene.xml";
	public const String cSchemaUri = "docs://generated/SceneSchema.json";

	/// The composed example scene, as a scene save writes it.
	public String ExampleXml = new .() ~ delete _;
	/// Schema, pretty printed: the bytes the resource serves.
	public String SchemaJson = new .() ~ delete _;
	public JsonValue Schema ~ delete _;

	/// Generates both documents from the engine composition (every manager and settings
	/// system, every factory description) and `builders` (cooked form to asset type). Reads
	/// declarations only, so every host produces the same bytes for the same code.
	public static SceneReference Generate(BuilderRegistry builders)
	{
		let reference = new SceneReference();
		let world = scope Scene("SceneReference");
		EngineSceneComposition.AddAllSceneManagers(world);
		// Fixed: the example's guids reproduce run after run.
		var rng = Sedulous.Core.Random(0x5CE7EF0247A7UL);
		let example = scope Example();
		ComposeExample(world, ref rng, example);

		// The schema's bodies first, over the DEFAULTS, before the example gets its content.
		let joiner = scope Joiner(builders);
		let schema = JsonValue.MakeObject();
		let components = ComponentsSection(world, example, joiner);
		let settings = SettingsSection(world, joiner);
		FillScriptBehaviour(world, example, ref rng);

		// The example: the very text a scene save stores.
		{
			let xml = scope XmlSerializer();
			SceneSerializer.SerializeScene(xml, world, .Referenced, true, .Text);
			if (xml.IsOk)
				xml.GetOutput(reference.ExampleXml);
			else
				GlobalLog(.Error, "Editor.Mcp: scene reference: the example scene did not serialize");
		}

		// The framing: the whole example stream recorded once.
		{
			let stream = scope SchemaRecorder();
			SceneSerializer.SerializeScene(stream, world, .Referenced, true, .Text);
			schema.Set("format", FormatSection(stream.Root));
		}
		schema.Set("components", components);
		schema.Set("settings", settings);
		schema.Set("scriptOverrides", ScriptOverridesSection());
		schema.ToString(reference.SchemaJson, true);
		reference.Schema = schema;
		return reference;
	}

	/// The schema entry for `name`, BORROWED: a component by wire name (a record's `type`) or
	/// type name, or a settings block by system id or type name; case folded. Null when none.
	public static JsonValue FindEntry(JsonValue schema, StringView name)
	{
		var found = EntryByName(schema.Get("components"), name, "wireName");
		if (found == null)
			found = EntryByName(schema.Get("settings"), name, "system");
		return found;
	}

	/// docs://generated/SceneExample.scene.xml (application/xml) and
	/// docs://generated/SceneSchema.json (application/json), serving this reference's bytes.
	public void RegisterResources(McpServer server)
	{
		let xml = new String(ExampleXml);
		server.RegisterResource(cExampleUri, "SceneExample.scene.xml", "application/xml",
			"generated by this host: a complete example scene - every component at its defaults, every settings block, a parent and child, a script behaviour with one override per property kind - exactly what scene_write accepts",
			new (outText, outError) => { outText.Append(xml); return true; }, xml);
		let json = new String(SchemaJson);
		server.RegisterResource(cSchemaUri, "SceneSchema.json", "application/json",
			"generated by this host: the scene format schema - stream framing, every component's and settings block's fields in wire order with kinds, defaults, enum names, ranges and reference targets, and the script override encoding",
			new (outText, outError) => { outText.Append(json); return true; }, json);
	}

	/// component_schema: one component's or settings block's schema entry by name.
	public void RegisterComponentSchemaTool(McpServer server)
	{
		let schema = Schema.Clone();
		let input = scope SchemaBuilder();
		input.Str("type", "component wire name / type name, or settings system id", true);
		server.RegisterTool("component_schema",
			"""
			One component's or settings block's schema entry from the generated scene format reference (docs://generated/SceneSchema.json): its fields in wire order with kinds, defaults, enum names, ranges and reference targets, plus its dataVersions. Pass `type`: a component's wire name (a record's `type`, e.g. "light") or type name, or a settings block's system id or type name. A name a component and a settings block share answers the component: the level script's block, whose system id is `script` like the Script component's, is `SceneScriptSettings`.
			""",
			input.Build(), .ReadOnly,
			new (arguments, outResult, outError) =>
			{
				let name = McpTools.ArgString(arguments, "type", .. scope .());
				if (name.IsEmpty)
				{
					outError.Append("`type` is required");
					return false;
				}
				let found = FindEntry(schema, name);
				if (found == null)
				{
					outError.AppendF("no component or settings block named '{}'. Components: {}. Settings: {}", name,
						EntryNames(schema.Get("components"), "wireName", .. scope .()),
						EntryNames(schema.Get("settings"), "system", .. scope .()));
					return false;
				}
				for (int i < found.Count)
					outResult.Set(found.KeyAt(i), found.Get(found.KeyAt(i)).Clone());
				return true;
			}, schema);
	}

	// ---- small text helpers ----------------------------------------------------------------

	private static void Hex(uint64 value, String outText) => outText.AppendF("0x{:X}", value);

	private static JsonValue Text(StringView text) => JsonValue.MakeString(text);

	private static JsonValue Decimal(uint64 value) => JsonValue.MakeString(value.ToString(.. scope .()));

	private static JsonValue HexJson(uint64 value) => JsonValue.MakeString(Hex(value, .. scope .()));

	/// A float as the number it reads as (0.1, not its double widening 0.10000000149011612).
	private static JsonValue FloatNumber(float value)
	{
		if (double.Parse(value.ToString(.. scope .())) case .Ok(let parsed))
			return JsonValue.MakeNumber(parsed);
		return JsonValue.MakeNumber(value);
	}

	private static StringView KindName(SchemaNode node)
	{
		switch (node.Kind)
		{
		case .Object: return "object";
		case .Array: return "array";
		case .Text: return "string";
		case .Guid: return "guid";
		case .Blob: return "blob";
		case .Scalar:
		}
		switch (node.Scalar)
		{
		case .Bool: return "bool";
		case .Int8: return "i8";
		case .UInt8: return "u8";
		case .Int16: return "i16";
		case .UInt16: return "u16";
		case .Int32: return "i32";
		case .UInt32: return "u32";
		case .Int64: return "i64";
		case .UInt64: return "u64";
		case .Float32: return "f32";
		case .Float64: return "f64";
		}
	}

	private static bool IsIntegerScalar(SchemaNode node) =>
		(node.Kind == .Scalar) && (node.Scalar != .Bool) && (node.Scalar != .Float32) && (node.Scalar != .Float64);

	private static JsonValue TypeJson(Type type)
	{
		let json = JsonValue.MakeObject();
		json.Set("name", Text(type.GetName(.. scope .())));
		let full = type.GetFullName(.. scope .());
		let name = type.GetName(.. scope .());
		let ns = (full.Length > name.Length + 1) ? StringView(full, 0, full.Length - name.Length - 1) : StringView();
		json.Set("namespace", Text(ns));
		let id = TypeIdOf(full);
		json.Set("id", Decimal(id));
		json.Set("idHex", HexJson(id));
		return json;
	}

	// ---- the reflection join ---------------------------------------------------------------

	/// A field's wire key is its name with the first letter lowercased (the generated
	/// Serialize's rule, and the one hand written bodies follow).
	private static bool KeyNames(StringView fieldName, StringView key)
	{
		if (fieldName.Length != key.Length)
			return false;
		if (fieldName.IsEmpty)
			return true;
		return (fieldName[0].ToLower == key[0].ToLower) && (StringView(fieldName, 1) == StringView(key, 1));
	}

	/// The reflected instance field of `owner` stored under `key`; null when none.
	private static FieldInfo? FindField(Type owner, StringView key)
	{
		if ((owner == null) || key.IsEmpty)
			return null;
		for (let field in owner.GetFields())
		{
			if (!field.IsStatic && KeyNames(field.Name, key))
				return field;
		}
		return null;
	}

	/// Whether anything is known about `type`'s fields: a type with no reflected field says
	/// nothing about its children, so they are not "unreflected", just unknown.
	private static bool HasReflectedFields(Type type)
	{
		if (type == null)
			return false;
		for (let field in type.GetFields())
		{
			if (!field.IsStatic)
				return true;
		}
		return false;
	}

	/// The element type of a List<T>, or null.
	private static Type ElementType(Type type)
	{
		if (let generic = type as SpecializedGenericType)
		{
			if (generic.UnspecializedType == typeof(List<>))
				return generic.GetGenericArg(0);
		}
		return null;
	}

	/// The reference join: `ref` for a reference shaped value type: "entity" for an EntityRef,
	/// {resource, asset} for a Ref<T>: the runtime type T, the factory DESCRIPTION the
	/// composition carries for it (its cooked form), the builder that produces that cooked
	/// form, its asset type. Nothing is constructed: the join reads declarations, so every host
	/// answers the same.
	private class Joiner
	{
		private BuilderRegistry mBuilders;
		private List<ResourceFactoryDesc*> mDescriptions = new .() ~ delete _;

		public this(BuilderRegistry builders)
		{
			mBuilders = builders;
			EngineComposition.FactoryDescriptions(mDescriptions);
		}

		/// Null for a type that is no reference; `resolved` false when no builder in this
		/// composition produces the cooked form (the asset is then omitted).
		public JsonValue RefJson(Type type, out bool resolved)
		{
			resolved = true;
			if (type == typeof(EntityRef))
				return Text("entity");
			let target = ReferenceShape.Target(type);
			if (target == null)
				return null;
			let json = JsonValue.MakeObject();
			json.Set("resource", Text(target.GetName(.. scope .())));
			// A factory that reads several cooked forms (a texture's, a render texture's) gives
			// several asset types: `asset` is the first, and `assets` lists them all when there
			// is more than one.
			let assets = scope List<Type>();
			if (mBuilders != null)
				SourceAssetTypesFor(mBuilders, target, assets, mDescriptions);
			if (assets.IsEmpty)
			{
				resolved = false;
				return json;
			}
			json.Set("asset", Text(assets[0].GetName(.. scope .())));
			if (assets.Count > 1)
			{
				let list = JsonValue.MakeArray();
				for (let asset in assets)
					list.Add(Text(asset.GetName(.. scope .())));
				json.Set("assets", list);
			}
			return json;
		}
	}

	/// The source asset types a resource reference to `product` takes: the runtime type's
	/// factory description in the engine composition gives its cooked forms, and the builder
	/// producing each gives its asset type (a texture's and a render texture's for a Texture).
	/// Declarations only, nothing constructed. Nothing is added when nothing in this
	/// composition makes the product. Shared by the schema and the editor's pickers.
	public static void SourceAssetTypesFor(BuilderRegistry builders, Type product, List<Type> outAssets,
		List<ResourceFactoryDesc*> descriptions = null)
	{
		var described = descriptions;
		if (described == null)
		{
			described = scope:: List<ResourceFactoryDesc*>();
			EngineComposition.FactoryDescriptions(described);
		}
		let cookedForms = scope List<Type>();
		for (let desc in described)
		{
			if (desc.Product == product)
			{
				desc.ForEachCooked(scope (cooked) => cookedForms.Add(cooked));
				break;
			}
		}
		for (let cooked in cookedForms)
		{
			if (cooked == null)
				continue;
			Type asset = null;
			builders.ForEach(scope [&](builder) =>
				{
					if ((asset == null) && (builder.ProductType == cooked))
						asset = builder.AssetType;
				});
			if (asset != null)
				outAssets.Add(asset);
		}
	}

	/// Where an annotation walk writes the keys with no reflected twin, and refs no factory
	/// resolves.
	private class FieldContext
	{
		public Joiner Joiner;
		public List<String> Unreflected;

		public this(Joiner joiner, List<String> unreflected)
		{
			Joiner = joiner;
			Unreflected = unreflected;
		}
	}

	/// One recorded node as a schema field. `field` is its reflected twin (null for none);
	/// `valueType` the reflected type of the value (the field's type, or a list's element type
	/// for an element).
	private static JsonValue FieldJson(SchemaNode node, FieldInfo? field, Type valueType, FieldContext ctx)
	{
		let json = JsonValue.MakeObject();
		if (!node.Key.IsEmpty)
			json.Set("key", Text(node.Key));
		json.Set("kind", Text(KindName(node)));
		switch (node.Kind)
		{
		case .Scalar, .Text, .Guid:
			json.Set("default", Text(node.Value));
		case .Blob:
			json.Set("blobSize", JsonValue.MakeNumber(node.BlobSize));
		case .Object:
			json.Set("fields", FieldsJson(node, valueType, ctx));
		case .Array:
			json.Set("count", JsonValue.MakeNumber(node.Count));
			let elementType = (valueType != null) ? ElementType(valueType) : null;
			if (elementType != null)
			{
				json.Set("elementType", Text(elementType.GetName(.. scope .())));
				let reference = ctx.Joiner.RefJson(elementType, var resolved);
				if (reference != null)
					json.Set("ref", reference);
			}
			// The first element stands for all of them: an object or one unkeyed value per
			// element, or, where elements write inline, the keyed run up to its first key again.
			if (let first = node.At(0))
			{
				if (first.Key.IsEmpty)
				{
					json.Set("element", FieldJson(first, null, elementType, ctx));
				}
				else
				{
					let run = JsonValue.MakeArray();
					for (int i < node.Children.Count)
					{
						let child = node.Children[i];
						if ((i > 0) && (child.Key == first.Key))
							break;
						let elementField = FindField(elementType, child.Key);
						if ((elementField == null) && HasReflectedFields(elementType))
							ctx.Unreflected.Add(new $"{node.Key}[].{child.Key}");
						run.Add(FieldJson(child, elementField, (elementField != null) ? elementField.Value.FieldType : null, ctx));
					}
					let element = JsonValue.MakeObject();
					element.Set("fields", run);
					json.Set("element", element);
				}
			}
		}

		if (field != null)
		{
			let info = field.Value;
			let type = info.FieldType;
			if (type.IsEnum && IsIntegerScalar(node))
			{
				let names = JsonValue.MakeArray();
				for (let (name, value) in Enum.GetEnumerator(type))
				{
					let entry = JsonValue.MakeObject();
					entry.Set("name", Text(name));
					entry.Set("value", JsonValue.MakeNumber(value));
					names.Add(entry);
				}
				json.Set("enum", names);
			}
			if (info.GetCustomAttribute<DisplayNameAttribute>() case .Ok(let display))
				json.Set("displayName", Text(display.Name));
			if (info.GetCustomAttribute<DescriptionAttribute>() case .Ok(let description))
				json.Set("description", Text(description.Text));
			if (info.GetCustomAttribute<CategoryAttribute>() case .Ok(let category))
				json.Set("category", Text(category.Name));
			if (info.GetCustomAttribute<RangeAttribute>() case .Ok(let range))
			{
				let bounds = JsonValue.MakeObject();
				bounds.Set("min", FloatNumber(range.Min));
				bounds.Set("max", FloatNumber(range.Max));
				bounds.Set("step", FloatNumber(range.Step));
				json.Set("range", bounds);
			}
			if (info.GetCustomAttribute<VisibleWhenAttribute>() case .Ok(let visible))
				json.Set("visibleWhen", Text(visible.Condition));
			let reference = ctx.Joiner.RefJson(type, var resolved);
			if (reference != null)
				json.Set("ref", reference);
			if (!resolved)
				ctx.Unreflected.Add(new .(node.Key));
		}
		return json;
	}

	/// `parent`'s children as the schema's `fields` array, each joined to `owner`'s reflected
	/// field of the same key (owner null: nothing known about this level).
	private static JsonValue FieldsJson(SchemaNode parent, Type owner, FieldContext ctx)
	{
		let fields = JsonValue.MakeArray();
		for (let child in parent.Children)
		{
			let field = FindField(owner, child.Key);
			if ((field == null) && HasReflectedFields(owner))
				ctx.Unreflected.Add(new .(child.Key));
			fields.Add(FieldJson(child, field, (field != null) ? field.Value.FieldType : null, ctx));
		}
		return fields;
	}

	private static JsonValue StringsJson(List<String> items)
	{
		let json = JsonValue.MakeArray();
		for (let item in items)
			json.Add(Text(item));
		return json;
	}

	/// The chain BeginVersionedPayload wrote. A component's or settings block's data version
	/// type id is TypeIdOf of its wire name or system id, which `typeName` names.
	private static JsonValue DataVersionsJson(Span<SerializedDataVersion> chain, StringView hashedName)
	{
		let json = JsonValue.MakeArray();
		for (let entry in chain)
		{
			let row = JsonValue.MakeObject();
			row.Set("type", Decimal(entry.TypeId));
			row.Set("typeHex", HexJson(entry.TypeId));
			if (TypeIdOf(hashedName) == entry.TypeId)
				row.Set("typeName", Text(hashedName));
			row.Set("version", JsonValue.MakeNumber(entry.Version));
			json.Add(row);
		}
		return json;
	}

	/// The recorded payload's own level: after the dataVersions array a versioned payload puts
	/// first, and inside the one unkeyed object a generated body opens.
	private static SchemaNode BodyOf(SchemaNode root, out int firstField)
	{
		firstField = ((root.At(0) != null) && (root.At(0).Key == "dataVersions")) ? 1 : 0;
		if ((root.Children.Count == firstField + 1) && (root.Children[firstField].Kind == .Object)
			&& root.Children[firstField].Key.IsEmpty)
		{
			firstField = 0;
			return root.Children[root.Children.Count - 1];
		}
		return root;
	}

	private static JsonValue BodyFieldsJson(SchemaNode root, Type owner, FieldContext ctx)
	{
		let body = BodyOf(root, let firstField);
		let fields = JsonValue.MakeArray();
		for (int i = firstField; i < body.Children.Count; i++)
		{
			let child = body.Children[i];
			let field = FindField(owner, child.Key);
			if ((field == null) && HasReflectedFields(owner))
				ctx.Unreflected.Add(new .(child.Key));
			fields.Add(FieldJson(child, field, (field != null) ? field.Value.FieldType : null, ctx));
		}
		return fields;
	}

	// ---- the example scene -----------------------------------------------------------------

	private class Example
	{
		public EntityHandle Root;
		public EntityHandle Child;
		/// The entity carrying each manager's component, by component type.
		public Dictionary<Type, EntityHandle> EntityByComponent = new .() ~ delete _;
	}

	/// Root and Child (the hierarchy pair), then one entity per serializable manager carrying
	/// that component at its defaults, named by its wire name. Guids from the seeded generator,
	/// in creation order.
	private static void ComposeExample(Scene world, ref Sedulous.Core.Random rng, Example example)
	{
		example.Root = world.CreateEntity(Guid.Generate(ref rng), "Root");
		example.Child = world.CreateEntity(Guid.Generate(ref rng), "Child");
		world.SetParent(example.Child, example.Root);
		let managers = scope List<ComponentManagerBase>();
		world.ForEachManager(scope (manager) => { if (manager.IsSerializable) managers.Add(manager); });
		for (let manager in managers)
		{
			let entity = world.CreateEntity(Guid.Generate(ref rng), manager.SerializationTypeId);
			world.SetParent(entity, example.Root);
			if (manager.AddDefaultComponent(entity))
				example.EntityByComponent[manager.ComponentType] = entity;
		}
	}

	private static ScriptPropertyValue SampleValue(ScriptPropertyType kind, Guid child, ref Sedulous.Core.Random rng)
	{
		switch (kind)
		{
		case .Float: return .Float(1.5);
		case .Int: return .Int(3);
		case .Bool: return .Bool(true);
		case .String: return .Str(new String("hello"));
		case .Color: return .Colour(.(1.0f, 0.5f, 0.25f, 1.0f));
		case .Vec3: return .Vec3(.(1.0f, 2.0f, 3.0f));
		case .Entity: return .Entity(child);
		case .Asset: return .Asset(Guid.Generate(ref rng));
		case .None: return .();
		}
	}

	/// After the schema recorded the defaults: the script component's entity gets one
	/// behaviour with an override of every property kind (named "<kind>Value"), so the example
	/// shows the override encoding the scriptOverrides section describes.
	private static void FillScriptBehaviour(Scene world, Example example, ref Sedulous.Core.Random rng)
	{
		let scripts = world.GetSystem<ScriptComponentManager>();
		if (scripts == null)
			return;
		if (!example.EntityByComponent.TryGetValue(typeof(ScriptComponent), let entity))
			return;
		let component = scripts.Get(entity);
		if ((component == null) || (component.Behaviors == null))
			return;
		let childId = world.GetEntityId(example.Child);
		let behaviour = new ScriptBehavior();
		behaviour.Script.Id = Guid.Generate(ref rng);
		for (let entry in ScriptPropertyNames.TypeNames)
		{
			let name = scope $"{entry.Name}Value";
			behaviour.SetOverride(ScriptPropertyNames.HashOf(name), SampleValue(entry.Kind, childId, ref rng));
		}
		component.Behaviors.Add(behaviour);
	}

	// ---- the schema's sections -------------------------------------------------------------

	/// The first record of an array: an object's children, or the keyed run up to its first key
	/// again when records write inline.
	private static void RecordNodes(SchemaNode array, List<SchemaNode> outNodes)
	{
		let first = array.At(0);
		if (first == null)
			return;
		if (first.Key.IsEmpty && (first.Kind == .Object))
		{
			outNodes.AddRange(first.Children);
			return;
		}
		for (int i < array.Children.Count)
		{
			let child = array.Children[i];
			if ((i > 0) && (child.Key == first.Key))
				break;
			outNodes.Add(child);
		}
	}

	private static JsonValue FormatSection(SchemaNode stream)
	{
		let json = JsonValue.MakeObject();
		json.Set("magic", Decimal(SceneStreamFormat.cMagic));
		json.Set("magicHex", HexJson(SceneStreamFormat.cMagic));
		json.Set("version", JsonValue.MakeNumber(SceneStreamFormat.cVersion));
		json.Set("sourceEncoding", Text("xml"));
		let sections = JsonValue.MakeArray();
		for (let child in stream.Children)
		{
			let section = JsonValue.MakeObject();
			section.Set("key", Text(child.Key));
			section.Set("kind", Text(KindName(child)));
			sections.Add(section);
		}
		json.Set("sections", sections);
		let prefabMode = JsonValue.MakeObject();
		prefabMode.Set("referenced", JsonValue.MakeNumber(SceneStreamFormat.cPrefabWireReferenced));
		prefabMode.Set("expanded", JsonValue.MakeNumber(SceneStreamFormat.cPrefabWireExpanded));
		json.Set("prefabModeValues", prefabMode);
		json.Set("typeIds", Text(scope $"a dataVersions type id is FNV-1a 64 over the UTF-8 bytes of the component's wire name or the settings block's system id: offset basis {FnvOffsetBasis}, prime {FnvPrime}"));
		json.Set("arrays", Text("an array carries its element count, then its elements: an object per element for a type that describes itself, one unkeyed value per scalar, string or guid element; a run of keyed fields per element where the writer lays elements inline (the run repeats from its first key)"));
		json.Set("structs", Text("a math value (Float2/3/4, Quaternion, Color) is an object of its named components; a component's fields follow its dataVersions directly inside the record's data object, and a settings block's inside its settings object"));

		let ctx = scope FieldContext(scope Joiner(null), scope List<String>());
		defer { ClearAndDeleteItems!(ctx.Unreflected); }
		// The entity record: the first entity's fields (the example's Root).
		if (let entities = stream.Find("entities"))
		{
			let nodes = scope List<SchemaNode>();
			RecordNodes(entities, nodes);
			let record = JsonValue.MakeArray();
			for (let node in nodes)
				record.Add(FieldJson(node, null, null, ctx));
			json.Set("entityRecord", record);
		}
		// The component record framing, its `data` standing for the component's own fields.
		if (let components = stream.Find("components"))
		{
			let nodes = scope List<SchemaNode>();
			RecordNodes(components, nodes);
			let record = JsonValue.MakeArray();
			for (let node in nodes)
			{
				let field = JsonValue.MakeObject();
				field.Set("key", Text(node.Key));
				field.Set("kind", Text(KindName(node)));
				if (node.Key == "data")
					field.Set("fields", Text("the component's dataVersions then its fields: components[].fields"));
				else if (node.Key == "type")
					field.Set("value", Text("the component's wireName"));
				else if (node.Key == "owner")
					field.Set("value", Text("the owning entity's id"));
				record.Add(field);
			}
			json.Set("componentRecord", record);
		}
		if (let settings = stream.Find("systemSettings"))
		{
			let nodes = scope List<SchemaNode>();
			RecordNodes(settings, nodes);
			let record = JsonValue.MakeArray();
			for (let node in nodes)
			{
				let field = JsonValue.MakeObject();
				field.Set("key", Text(node.Key));
				field.Set("kind", Text(KindName(node)));
				if (node.Key == "settings")
					field.Set("fields", Text("the block's fields: settings[].fields"));
				else if (node.Key == "system")
					field.Set("value", Text("the block's system id"));
				else if (node.Key == "dataVersions")
					field.Set("value", Text("the block's dataVersions"));
				record.Add(field);
			}
			json.Set("settingsRecord", record);
		}
		json.Set("prefabInstanceRecord", PrefabInstanceRecord());
		return json;
	}

	/// The keys of one prefabInstances element, in the order the reader takes them
	/// (PrefabRecordSerializer); the example scene has no instance to derive them from, so they
	/// are spelled out here and a test holds them to the serializer's output.
	public static readonly String[?] cPrefabInstanceKeys = .("prefab", "parent", "position", "rotation", "scale",
		"rootLive", "owner", "nestedSrcRoot", "nextSibling", "placement", "members", "destroyed",
		"transformOverrides", "componentOps");

	/// One prefabInstances element: the minimal form an author writes is the prefab, where
	/// its root goes, and empty maps; a save fills the maps in.
	private static JsonValue PrefabInstanceRecord()
	{
		let record = JsonValue.MakeArray();
		void Field(StringView key, StringView kind, StringView value)
		{
			let field = JsonValue.MakeObject();
			field.Set("key", Text(key));
			field.Set("kind", Text(kind));
			field.Set("value", Text(value));
			record.Add(field);
		}
		Field("prefab", "guid", "the prefab asset's guid (asset_list: type PrefabDocument; an imported model's is the `Prefab` beside its manifest)");
		Field("parent", "guid", "the entity the instance root sits under; nil for a scene root");
		Field("position", "object", "the instance root's local position {x, y, z}");
		Field("rotation", "object", "the instance root's local rotation {x, y, z, w}");
		Field("scale", "object", "the instance root's local scale {x, y, z}");
		Field("rootLive", "guid", "the instance root's entity id as last saved; any fresh guid when authoring");
		Field("owner", "guid", "nil; a nested instance's owning instance root");
		Field("nestedSrcRoot", "guid", "nil; a nested instance's root in its owner's prefab");
		Field("nextSibling", "guid", "nil, or the entity the root sits before among its siblings");
		Field("placement", "u8", "1: the transform above places the root");
		Field("members", "array", "the prefab's entity ids paired with the instance's ({src, live} per member); EMPTY when authoring: the load mints fresh ids, and a save records them");
		Field("destroyed", "array", "members deleted out of the instance; empty when authoring");
		Field("transformOverrides", "array", "member transforms changed from the prefab; empty when authoring");
		Field("componentOps", "array", "member components added, removed or changed from the prefab; empty when authoring");
		let wrapped = JsonValue.MakeObject();
		wrapped.Set("mode", Text("prefabMode must be 4 (referenced) for prefabInstances to be read; each element is a run of these keys, in this order, laid inline in the array"));
		wrapped.Set("fields", record);
		return wrapped;
	}

	private static JsonValue ComponentsSection(Scene world, Example example, Joiner joiner)
	{
		let json = JsonValue.MakeArray();
		let managers = scope List<ComponentManagerBase>();
		world.ForEachManager(scope (manager) => { if (manager.IsSerializable) managers.Add(manager); });
		for (let manager in managers)
		{
			let type = manager.ComponentType;
			let entry = JsonValue.MakeObject();
			entry.Set("wireName", Text(manager.SerializationTypeId));
			entry.Set("type", TypeJson(type));
			if (!example.EntityByComponent.TryGetValue(type, let entity))
			{
				entry.Set("recorded", JsonValue.MakeBool(false));
				json.Add(entry);
				continue;
			}
			let recorder = scope SchemaRecorder();
			manager.WriteComponent(recorder, entity);
			entry.Set("dataVersions", DataVersionsJson(recorder.VersionChain, manager.SerializationTypeId));
			let unreflected = scope List<String>();
			defer { ClearAndDeleteItems!(unreflected); }
			entry.Set("fields", BodyFieldsJson(recorder.Root, type, scope FieldContext(joiner, unreflected)));
			entry.Set("unreflected", StringsJson(unreflected));
			json.Add(entry);
		}
		return json;
	}

	private static JsonValue SettingsSection(Scene world, Joiner joiner)
	{
		let json = JsonValue.MakeArray();
		for (let system in world.Systems)
		{
			let type = system.SettingsType;
			if (type == null)
				continue;
			// Exactly the framing the scene save writes for a text settings record.
			let recorder = scope SchemaRecorder();
			BeginVersionedPayload(recorder, TypeIdOf(system.SettingsId), system.SettingsDataVersion, system.SettingsMinReadDataVersion);
			recorder.Key("settings");
			recorder.BeginObject();
			system.SerializeSettings(recorder);
			recorder.EndObject();
			EndVersionedPayload(recorder);

			let entry = JsonValue.MakeObject();
			entry.Set("system", Text(system.SettingsId));
			entry.Set("type", TypeJson(type));
			entry.Set("dataVersions", DataVersionsJson(recorder.VersionChain, system.SettingsId));
			let unreflected = scope List<String>();
			defer { ClearAndDeleteItems!(unreflected); }
			let ctx = scope FieldContext(joiner, unreflected);
			if (let settings = recorder.Root.Find("settings"))
				entry.Set("fields", BodyFieldsJson(settings, type, ctx));
			else
				entry.Set("fields", JsonValue.MakeArray());
			entry.Set("unreflected", StringsJson(unreflected));
			json.Add(entry);
		}
		return json;
	}

	private static JsonValue ScriptOverridesSection()
	{
		let json = JsonValue.MakeObject();
		let ctx = scope FieldContext(scope Joiner(null), scope List<String>());
		defer { ClearAndDeleteItems!(ctx.Unreflected); }

		// The override record as the script component writes it.
		{
			let recorder = scope SchemaRecorder();
			let record = scope ScriptPropertyOverride();
			record.Serialize(recorder);
			json.Set("record", FieldsJson(recorder.Root, null, ctx));
		}
		// The hash, with a worked example a reader can check.
		{
			let hash = JsonValue.MakeObject();
			hash.Set("algorithm", Text(scope $"FNV-1a style, 64-bit, over the UTF-8 bytes of the property name: offset basis {FnvOffsetBasis}, prime {FnvPrime}, no terminator"));
			let example = JsonValue.MakeObject();
			example.Set("name", Text("speed"));
			example.Set("nameHash", Decimal(ScriptPropertyNames.HashOf("speed")));
			hash.Set("example", example);
			json.Set("hash", hash);
		}
		// Every kind: its number on the wire, its authored spelling, and the payload key the
		// value uses, taken from the value's own Serialize, one kind at a time.
		{
			let kinds = JsonValue.MakeArray();
			for (let entry in ScriptPropertyNames.TypeNames)
			{
				var value = ScriptPropertyValue();
				value.Kind = entry.Kind;
				let recorder = scope SchemaRecorder();
				value.Serialize(recorder);
				if (value.Text != null)
					delete value.Text;
				let kind = JsonValue.MakeObject();
				kind.Set("kind", JsonValue.MakeNumber((uint8)entry.Kind));
				kind.Set("name", Text(entry.Name));
				if (entry.Kind == .Asset)
					kind.Set("authoredAs", Text(scope $"{ScriptPropertyNames.cAssetTypePrefix}<TypeName>"));
				let payload = JsonValue.MakeArray();
				for (let field in recorder.Root.Children)
				{
					if (field.Key == "kind")
						continue;
					let key = JsonValue.MakeObject();
					key.Set("key", Text(field.Key));
					key.Set("kind", Text(KindName(field)));
					if (field.Kind == .Object)
						key.Set("fields", FieldsJson(field, null, ctx));
					payload.Add(key);
				}
				kind.Set("payload", payload);
				kinds.Add(kind);
			}
			json.Set("kinds", kinds);
		}
		return json;
	}

	private static JsonValue EntryByName(JsonValue entries, StringView name, StringView wireKey)
	{
		if (entries == null)
			return null;
		for (int i < entries.Count)
		{
			let entry = entries.At(i);
			let wire = entry.Get(wireKey);
			let type = entry.Get("type");
			if (((wire != null) && StringView.Compare(wire.AsString(), name, true) == 0)
				|| ((type != null) && (type.Get("name") != null) && (StringView.Compare(type.Get("name").AsString(), name, true) == 0)))
				return entry;
		}
		return null;
	}

	private static void EntryNames(JsonValue entries, StringView wireKey, String outNames)
	{
		if (entries == null)
			return;
		for (int i < entries.Count)
		{
			if (!outNames.IsEmpty)
				outNames.Append(", ");
			if (let wire = entries.At(i).Get(wireKey))
				outNames.Append(wire.AsString());
		}
	}
}
