FileVersion = 1

[Project]
Name = "Sedulous.Navigation"
TargetType = "BeefLib"
StartupObject = "Sedulous.Navigation.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"recastnavigation-Beef" = "*"
