FileVersion = 1

[Project]
Name = "Sedulous.RHI.Validation.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.RHI.Validation.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.RHI.Validation" = "*"
