FileVersion = 1

[Project]
Name = "LegacyGUISandbox"
StartupObject = "LegacyGUISandbox.Program"
DefaultNamespace = "LegacyGUISandbox"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Images.SDL" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.LegacyGUI" = "*"
"Sedulous.LegacyGUI.Shell" = "*"
"Sedulous.Drawing.Renderer" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Fonts.TTF" = "*"
