FileVersion = 1

[Project]
Name = "Sedulous.Editor.Core.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Core.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Xml.Serialization" = "*"
"Sedulous.Engine.Project" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Cook" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Pipeline.Registration" = "*"
"Sedulous.Script.Resource" = "*"
"Sedulous.Image" = "*"
"Sedulous.UI" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Settings" = "*"
"Sedulous.Editor.Core" = "*"
