FileVersion = 1

[Project]
Name = "Samples.RHI.Sample024_OcclusionQuery"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.RHI.Sample024_OcclusionQuery.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Samples.Framework" = "*"
