FileVersion = 1

[Project]
Name = "Sedulous.Materials.PipelineCache.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Materials.PipelineCache.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Materials.PipelineCache" = "*"
