FileVersion = 1

[Project]
Name = "Sedulous.Tools.Editor"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Tools.Editor.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Project" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Pipeline.Registration" = "*"
"Sedulous.Geometry.Pipeline" = "*"
"Sedulous.Fonts.Pipeline" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.Input.Pipeline" = "*"
"Sedulous.Physics.Pipeline" = "*"
"Sedulous.Navigation.Pipeline" = "*"
"Sedulous.Audio.Pipeline" = "*"
"Sedulous.UI.Pipeline" = "*"
"Sedulous.Heightfield.Pipeline" = "*"
"Sedulous.Terrain.Pipeline" = "*"
"Sedulous.Vegetation.Pipeline" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
"Sedulous.Editor.Scene" = "*"
"Sedulous.Editor.Input" = "*"
"Sedulous.Editor.Navigation" = "*"
"Sedulous.Editor.PropertyAnimation" = "*"
"Sedulous.Editor.GameUI" = "*"
"Sedulous.Editor.Audio" = "*"
"Sedulous.Editor.Texture" = "*"
"Sedulous.Editor.Image" = "*"
"Sedulous.Editor.Heightfield" = "*"
"Sedulous.Editor.Terrain" = "*"
"Sedulous.Editor.Vegetation" = "*"
"Sedulous.Editor.Spline" = "*"
"Sedulous.Editor.Fonts" = "*"
"Sedulous.Editor.Physics" = "*"
"Sedulous.Editor.Generic" = "*"
"Sedulous.Editor.Script" = "*"
"Sedulous.Editor.Script.AngelScript" = "*"
