FileVersion = 1

[Project]
Name = "Sedulous.Engine.Animation"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Animation.Resources" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Core.Mathematics" = "*"
