FileVersion = 1

[Project]
Name = "Samples.Framework"
TargetType = "BeefLib"
StartupObject = "Samples.Framework.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Bulkan" = "*"
"SDL3" = "*"
"Dxc-Beef" = "*"
