FileVersion = 1

[Project]
Name = "Sedulous.UI.Viewport"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI.Viewport.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.UI" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
