FileVersion = 1

[Project]
Name = "Sedulous.Editor.Scene"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Scene.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Settings" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Model.Resource" = "*"
"Sedulous.ModelImporter" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Render" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.Spline" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Navigation" = "*"
"Sedulous.Engine.Spline" = "*"
"Sedulous.Engine.Particles" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
