FileVersion = 1

[Project]
Name = "Sedulous.Editor.Scene"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Scene.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Settings" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Render" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
