FileVersion = 1

[Project]
Name = "Sedulous.Editor.Scene"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Scene.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Editor.Core" = "*"
