FileVersion = 1

[Project]
Name = "ImGuiSample"
StartupObject = "ImGuiSample.Program"

[Dependencies]
corlib = "*"
RuntimeSampleFramework = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"cimgui-Beef" = "*"
