FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Runtime" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Resources" = "*", "Sedulous.Jobs" = "*", "Sedulous.Shell" = "*", "Sedulous.UI" = "*", "Sedulous.UI.Toolkit" = "*", "Sedulous.Renderer" = "*", "Sedulous.Images" = "*"}

[Project]
Name = "Sedulous.Editor.Core"
TargetType = "BeefLib"
