FileVersion = 1

[Project]
Name = "Sedulous.Editor.Core"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Engine.App" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Jobs" = "*"
"Sedulous.Shell" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Renderer" = "*"
"Sedulous.Images" = "*"
"Sedulous.Images.IO" = "*"
"Sedulous.Serialization" = "*"
"Sedulous.Core.Logging" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VFS.Disk" = "*"
