FileVersion = 1

[Project]
Name = "Sedulous.Editor.Core"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Core.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Xml.Serialization" = "*"
"Sedulous.Engine.Project" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Settings" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
