FileVersion = 1

[Project]
Name = "Sedulous.Materials.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Materials.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
