FileVersion = 1

[Project]
Name = "Sedulous.Texture.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Texture.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Texture.Resource" = "*"
