FileVersion = 1

[Project]
Name = "Sedulous.Texture.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Texture.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Resource" = "*"
