FileVersion = 1

[Project]
Name = "Sedulous.Pipeline.ScriptSurface"
TargetType = "BeefLib"
StartupObject = "Sedulous.Pipeline.ScriptSurface.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Script" = "*"
"Sedulous.Engine.ScriptSurface" = "*"
"Sedulous.Animation.Pipeline" = "*"
"Sedulous.Audio.Pipeline" = "*"
"Sedulous.Fonts.Pipeline" = "*"
"Sedulous.Geometry.Pipeline" = "*"
"Sedulous.Heightfield.Pipeline" = "*"
"Sedulous.Image.Pipeline" = "*"
"Sedulous.Input.Pipeline" = "*"
"Sedulous.Materials.Pipeline" = "*"
"Sedulous.ModelImporter" = "*"
"Sedulous.Navigation.Pipeline" = "*"
"Sedulous.Particles.Pipeline" = "*"
"Sedulous.Physics.Pipeline" = "*"
"Sedulous.Pipeline.Cook" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.PropertyAnimation.Pipeline" = "*"
"Sedulous.Script.AngelScript.Pipeline" = "*"
"Sedulous.Script.Pipeline" = "*"
"Sedulous.Shaders.Pipeline" = "*"
"Sedulous.Terrain.Pipeline" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.UI.Pipeline" = "*"
