FileVersion = 1

[Project]
Name = "AudioSandbox"
StartupObject = "AudioSandbox.Program"

[Dependencies]
corlib = "*"
RuntimeSampleFramework = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Audio" = "*"
"Sedulous.Audio.SDL3" = "*"
"Sedulous.Audio.Decoders" = "*"
"Sedulous.RHI" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Shell" = "*"
