FileVersion = 1

[Project]
Name = "Sedulous.Engine.Spline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Spline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Spline" = "*"
