FileVersion = 1

[Project]
Name = "Sedulous.Engine.GameInstance.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.GameInstance.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.GameInstance" = "*"
"Sedulous.Engine.Net" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Input" = "*"
"Sedulous.Messaging" = "*"
"Sedulous.Net" = "*"
"Sedulous.Net.Manager" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Shell" = "*"
"Sedulous.VFS" = "*"
