FileVersion = 1

[Project]
Name = "Sedulous.Runtime.Client"
TargetType = "BeefLib"
StartupObject = "Sedulous.Runtime.Client.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Shell" = "*"
