FileVersion = 1

[Project]
Name = "Sedulous.Runtime.Client"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.Platform" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Jobs" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VFS.Disk" = "*"
"Sedulous.Core.Mathematics" = "*"
