FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample009_Mipmaps"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample009_Mipmaps.Program"

[Dependencies]
corlib = "*"
