FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Runtime" = "*", "Sedulous.Scenes" = "*", "Sedulous.Engine.Runtime" = "*", "Sedulous.RHI" = "*", "Sedulous.Shell" = "*", "Sedulous.Renderer" = "*", "Sedulous.Shaders" = "*", "Sedulous.RenderGraph" = "*", "Sedulous.Materials" = "*", "Sedulous.Core.Mathematics" = "*"}

[Project]
Name = "Sedulous.Engine.Render"
TargetType = "BeefLib"
