FileVersion = 1

[Project]
Name = "Sedulous.Engine.Render"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Render.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.PipelineCache" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.Render" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Profiler" = "*"
