FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Runtime" = "*", "Sedulous.Scenes" = "*", "Sedulous.Engine.Runtime" = "*", "Sedulous.RHI" = "*", "Sedulous.Shell" = "*", "Sedulous.Renderer" = "*", "Sedulous.Shaders" = "*", "Sedulous.RenderGraph" = "*", "Sedulous.Materials" = "*", "Sedulous.Materials.Resources" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Resources" = "*", "Sedulous.Profiler" = "*", "Sedulous.Animation" = "*", "Sedulous.Geometry" = "*", "Sedulous.Geometry.Resources" = "*", "Sedulous.Textures.Resources" = "*", "Sedulous.Imaging" = "*"}

[Project]
Name = "Sedulous.Engine.Render"
TargetType = "BeefLib"
