FileVersion = 1

[Project]
Name = "Sedulous.UI.Application.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI.Application.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Shell" = "*"
"Sedulous.UI.Application" = "*"
