FileVersion = 1

[Project]
Name = "Sedulous.UI.Application.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI.Application.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Null" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Shell.Null" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Application" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.UI.Toolkit" = "*"
