FileVersion = 1

[Project]
Name = "Sedulous.Editor.ViewportTools.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.ViewportTools.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Render" = "*"
"Sedulous.Editor.ViewportTools" = "*"
