FileVersion = 1

[Project]
Name = "Sedulous.Geometry.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Geometry.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
