FileVersion = 1

[Project]
Name = "Sedulous.Editor.Terrain.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Terrain.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Editor.Terrain" = "*"
