FileVersion = 1

[Project]
Name = "Sedulous.Editor.Terrain.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Terrain.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Image" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Render" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Heightfield.Resource" = "*"
"Sedulous.Heightfield.Pipeline" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Terrain.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.UI" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
"Sedulous.Editor.App" = "*"
"Sedulous.Editor.Terrain" = "*"
