FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample008_DepthBuffer"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample008_DepthBuffer.Program"

[Dependencies]
corlib = "*"
