FileVersion = 1

[Project]
Name = "Sedulous.Geometry.Tooling"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Models" = "*"
"Sedulous.Images" = "*"
"Sedulous.Animation" = "*"
corlib = "*"
"Sedulous.Images.Loading" = "*"
