FileVersion = 1

[Project]
Name = "Sedulous.Engine.Integration.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Integration.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Messaging" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Script" = "*"
"Sedulous.Script.Resource" = "*"
"Sedulous.Script.AngelScript" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Script" = "*"
"Sedulous.Engine.ScriptSurface" = "*"
"Sedulous.Engine.Integration" = "*"
