FileVersion = 1

[Project]
Name = "Sedulous.Particles.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Particles.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Resource" = "*"
