FileVersion = 1

[Project]
Name = "Sedulous.Texture.Compression"
TargetType = "BeefLib"
StartupObject = "Sedulous.Texture.Compression.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"astcenc-Beef" = "*"
"bc7enc-Beef" = "*"
