FileVersion = 1

[Project]
Name = "Sedulous.Shaders.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Shaders.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Shaders.Resource" = "*"
