FileVersion = 1

[Project]
Name = "Sedulous.Editor.Fonts"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Fonts.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Image" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Coverage" = "*"
"Sedulous.Fonts.Coverage.Baker" = "*"
"Sedulous.Fonts.DistanceField" = "*"
"Sedulous.Fonts.DistanceField.Baker" = "*"
"Sedulous.Fonts.TrueType" = "*"
"Sedulous.Fonts.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
