FileVersion = 1

[Project]
Name = "Sedulous.Script.Fixture"
TargetType = "BeefLib"
StartupObject = "Sedulous.Script.Fixture.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Script" = "*"
