FileVersion = 1

[Project]
Name = "Samples.Sandbox"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.Sandbox.Program"

[Dependencies]
corlib = "*"
"Samples.Common" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Engine.Particles" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Extensions.Imgui" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Model" = "*"
"Sedulous.Model.Resource" = "*"
"Sedulous.ModelImporter" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Render" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.VFS" = "*"
