FileVersion = 1

[Project]
Name = "Sedulous.Engine.Net.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Net.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Net" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Net.Manager" = "*"
"Sedulous.Engine.Net" = "*"
