FileVersion = 1

[Project]
Name = "Sedulous.Scripting.Null"
TargetType = "BeefLib"
StartupObject = "Sedulous.Scripting.Null.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Scripting" = "*"
