FileVersion = 1

[Project]
Name = "Sedulous.RHI.Vulkan"
TargetType = "BeefLib"
StartupObject = "Sedulous.RHI.Vulkan.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Bulkan" = "*"
