FileVersion = 1

[Project]
Name = "Sedulous.Runtime.Web"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.Web" = "*"
