FileVersion = 1

[Project]
Name = "Sedulous.Render.Api"
TargetType = "BeefLib"
StartupObject = "Sedulous.Render.Api.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Scene" = "*"
