FileVersion = 1

[Project]
Name = "Sedulous.Materials.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Materials.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Shaders.Resource" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Resource" = "*"
