FileVersion = 1

[Project]
Name = "Sedulous.Terrain.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Terrain.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Terrain" = "*"
"Sedulous.Texture.Resource" = "*"
