FileVersion = 1

[Project]
Name = "Sedulous.Texture.Compression.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Texture.Compression.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Texture.Compression" = "*"
"astcenc-Beef" = "*"
"bc7enc-Beef" = "*"
"bcdec-Beef" = "*"
