FileVersion = 1

[Project]
Name = "Sedulous.Engine.Physics"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Physics.Jolt" = "*"
"Sedulous.Core.Mathematics" = "*"
