FileVersion = 1

[Project]
Name = "Sedulous.Engine.Physics"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Physics.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Render" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
