FileVersion = 1

[Project]
Name = "Sedulous.Engine.DefaultApp"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.DefaultApp.Program"

[Dependencies]
corlib = "*"
"Sedulous.Audio" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Input" = "*"
"Sedulous.Net" = "*"
"Sedulous.Net.Manager" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Scene" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Audio.Resource" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Heightfield.Resource" = "*"
"Sedulous.Image.Resource" = "*"
"Sedulous.Input.Resource" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Model.Resource" = "*"
"Sedulous.Navigation.Resource" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.PropertyAnimation.Resource" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Shaders.Resource" = "*"
"Sedulous.PropertyAnimation" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Model" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Navigation" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Terrain" = "*"
"Sedulous.Texture" = "*"
"Sedulous.UI" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Engine.GameInstance" = "*"
"Sedulous.Engine.Input" = "*"
"Sedulous.Engine.Integration" = "*"
"Sedulous.Engine.Navigation" = "*"
"Sedulous.Engine.Net" = "*"
"Sedulous.Engine.Particles" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.SceneSurface" = "*"
"Sedulous.Engine.Script" = "*"
"Sedulous.Engine.Script.Facades" = "*"
"Sedulous.Engine.ScriptSurface" = "*"
"Sedulous.Script" = "*"
"Sedulous.Script.AngelScript" = "*"
"Sedulous.Script.Resource" = "*"
"Sedulous.Engine.Spline" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Engine.Vegetation" = "*"
"Sedulous.Vegetation.Resource" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.Engine.UI.Script" = "*"
