FileVersion = 1

[Project]
Name = "Sedulous.Engine.Navigation"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
recastnavigation-Beef = "*"
