FileVersion = 1

[Project]
Name = "Sedulous.Net.Manager"
TargetType = "BeefLib"
StartupObject = "Sedulous.Net.Manager.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Net.WebSocket" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Profiler" = "*"
