FileVersion = 1

[Project]
Name = "Sedulous.Render"
TargetType = "BeefLib"
StartupObject = "Sedulous.Render.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.RenderGraph" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.PipelineCache" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Lod" = "*"
