FileVersion = 1

[Project]
Name = "Sedulous.Engine.UI"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.UI.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Input" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Gamekit" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.UI.Shell" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.Fonts.TrueType" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.Engine.Input" = "*"
"Sedulous.Engine.Scene" = "*"
