FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Runtime" = "*", "Sedulous.Shell" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.UI" = "*", "Sedulous.UI.Runtime" = "*", "Sedulous.UI.Shell" = "*", "Sedulous.VG" = "*", "Sedulous.VG.Renderer" = "*", "Sedulous.Fonts" = "*", "Sedulous.Fonts.TTF" = "*", "Sedulous.Shaders" = "*", "Sedulous.RHI" = "*", "Sedulous.Images" = "*", "Sedulous.Renderer" = "*", "Sedulous.Materials" = "*", "Sedulous.Core.Mathematics" = "*"}

[Project]
Name = "Sedulous.Engine.UI"
TargetType = "BeefLib"
