FileVersion = 1

[Project]
Name = "Sedulous.Pipeline.Core"
TargetType = "BeefLib"
StartupObject = "Sedulous.Pipeline.Core.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
