FileVersion = 1

[Project]
Name = "Samples.UISandbox"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.UISandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TrueType" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.Image" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Application" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.UI.Shell" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.UI.VFS" = "*"
"Sedulous.UI.Viewport" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.VG.SVG" = "*"
