FileVersion = 1

[Project]
Name = "DrawingSandbox"
StartupObject = "DrawingSandbox.Program"

[Dependencies]
corlib = "*"
RuntimeSampleFramework = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Drawing.Renderer" = "*"
