FileVersion = 1

[Project]
Name = "Sedulous.UI.Gamekit.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI.Gamekit.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Input" = "*"
"Sedulous.Shell" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Gamekit" = "*"
"Sedulous.VG" = "*"
