FileVersion = 1

[Project]
Name = "Sedulous.Mcp.Reflection"
TargetType = "BeefLib"
StartupObject = "Sedulous.Mcp.Reflection.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Json" = "*"
"Sedulous.Mcp" = "*"
