FileVersion = 1

[Project]
Name = "Sedulous.Engine.Audio.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Audio.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Audio" = "*"
"Sedulous.Core" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Settings" = "*"
