FileVersion = 1

[Project]
Name = "Sedulous.Input.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Input.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Input" = "*"
