FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Coverage.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Fonts.Coverage.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Fonts.Coverage" = "*"
