FileVersion = 1

[Project]
Name = "Sedulous.Image.DDS"
TargetType = "BeefLib"
StartupObject = "Sedulous.Image.DDS.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"bcdec-Beef" = "*"
