FileVersion = 1

[Project]
Name = "Sedulous.Editor.Preview"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Preview.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Image" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Render" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.UI.Viewport" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.Camera" = "*"
