FileVersion = 1

[Project]
Name = "Sedulous.Editor.Input"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Input.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Input" = "*"
"Sedulous.Input.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
