FileVersion = 1

[Project]
Name = "Sedulous.RHI.Null.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.RHI.Null.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
