FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample030_RenderBundles"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample030_RenderBundles.Program"

[Dependencies]
corlib = "*"
