FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.App" = "*", "Sedulous.Engine.Runtime" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Scenes" = "*", "Sedulous.Runtime" = "*", "Sedulous.Renderer" = "*", "Sedulous.RHI" = "*", "Sedulous.Core.Mathematics" = "*"}

[Project]
Name = "EngineSandbox"
TargetType = "BeefConsoleApplication"
StartupObject = "EngineSandbox.Program"
