FileVersion = 1

[Project]
Name = "Sedulous.Geometry.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Geometry.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Resource" = "*"
