FileVersion = 1

[Project]
Name = "Sedulous.Shaders.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Shaders.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Shaders.Pipeline" = "*"
"Sedulous.Shaders.Resource" = "*"
"Sedulous.VFS" = "*"
