FileVersion = 1

[Project]
Name = "Sedulous.Editor.Image.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Image.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.Pipeline" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.Image" = "*"
