FileVersion = 1

[Project]
Name = "Sedulous.Engine.Net"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Net.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Net.Manager" = "*"
