FileVersion = 1

[Project]
Name = "Sedulous.Engine.UI.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.UI.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Input" = "*"
"Sedulous.Render" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.Null" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.Engine.Input" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.UI" = "*"
