FileVersion = 1

[Project]
Name = "Sedulous.Engine.Terrain"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Terrain.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Render" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Terrain" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
