FileVersion = 1

[Project]
Name = "Sedulous.Editor.Physics"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Physics.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.Physics.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Render" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
"Sedulous.Editor.Preview" = "*"
