FileVersion = 1

[Project]
Name = "Samples.TerrainPlayground"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.TerrainPlayground.Program"

[Dependencies]
corlib = "*"
"Samples.Common" = "*"
"Sedulous.Core" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Extensions.Imgui" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Materials" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Vegetation" = "*"
"Sedulous.Engine.Vegetation" = "*"
