FileVersion = 1

[Project]
Name = "Samples.NetEcho"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.NetEcho.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
