FileVersion = 1

[Project]
Name = "Sedulous.Engine.Player"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Player.Program"

[Dependencies]
corlib = "*"
"Sedulous.Audio" = "*"
"Sedulous.Audio.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Input" = "*"
"Sedulous.Input.Resource" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Settings" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VFS.Pak" = "*"
"Sedulous.Xml" = "*"
"Sedulous.Xml.Serialization" = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Engine.GameInstance" = "*"
"Sedulous.Script.Resource" = "*"
"Sedulous.Engine.Project" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.UI" = "*"
