FileVersion = 1

[Project]
Name = "stb_image-Beef"
TargetType = "BeefLib"
StartupObject = "stb_image_Beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/stb_image.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/stb_image.lib"]

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)/dist/Release-Linux64/libstb_image.a"]

[Configs.Release.Linux64]
LibPaths = ["$(ProjectDir)/dist/Release-Linux64/libstb_image.a"]

[Configs.Test.Linux64]
LibPaths = ["$(ProjectDir)/dist/Release-Linux64/libstb_image.a"]
