FileVersion = 1

[Project]
Name = "Sedulous.Input.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Input.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Input" = "*"
"Sedulous.Input.Resource" = "*"
