FileVersion = 1

[Project]
Name = "Sedulous.Runtime.SDL3.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Runtime.SDL3.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"SDL3" = "*"
