FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample012_Wireframe"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample012_Wireframe.Program"

[Dependencies]
corlib = "*"
