FileVersion = 1

[Project]
Name = "Sedulous.UI.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Resource" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Gamekit" = "*"
"Sedulous.UI.Pipeline" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.VFS" = "*"
