FileVersion = 1

[Project]
Name = "Sedulous.Settings.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Settings.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Settings" = "*"
"Sedulous.Core" = "*"
"Sedulous.Xml" = "*"
"Sedulous.Xml.Serialization" = "*"
