using System;
namespace wgpu_Beef;

// GENERATED by generate.py from the vendored headers. Do not edit by hand:
// a wgpu-native bump is a re-run, and a hand edit is lost by the next one.

typealias WGPUSubmissionIndex = uint64;


static
{
}

enum WGPUNativeSType : int32
{
	WGPUSType_DeviceExtras = 0x00030001,
	WGPUSType_NativeLimits = 0x00030002,
	WGPUSType_ShaderSourceGLSL = 0x00030003,
	WGPUSType_InstanceExtras = 0x00030004,
	WGPUSType_BindGroupEntryExtras = 0x00030005,
	WGPUSType_BindGroupLayoutEntryExtras = 0x00030006,
	WGPUSType_QuerySetDescriptorExtras = 0x00030007,
	WGPUSType_SurfaceConfigurationExtras = 0x00030008,
	WGPUSType_SurfaceSourceSwapChainPanel = 0x00030009,
	WGPUSType_PrimitiveStateExtras = 0x0003000A,
	WGPUSType_SamplerDescriptorExtras = 0x0003000B,
	WGPUNativeSType_Force32 = 0x7FFFFFFF
}

/**
 * Additional surface-get-current-texture status codes defined by wgpu-native.
 *
 * These extend the standard @c WGPUSurfaceGetCurrentTextureStatus values.
 */
enum WGPUNativeSurfaceGetCurrentTextureStatus : int32
{
	WGPUSurfaceGetCurrentTextureStatus_Occluded = 0x00030001,
	WGPUNativeSurfaceGetCurrentTextureStatus_Force32 = 0x7FFFFFFF
}

/**
 * Native-only device features.
 *
 * These extend the standard @c WGPUFeatureName values and can be passed to
 * @c WGPUDeviceDescriptor::requiredFeatures to request additional
 * capabilities when creating a device.
 */
enum WGPUNativeFeature : int32
{
	WGPUNativeFeature_Immediates = 0x00030001,
	WGPUNativeFeature_TextureAdapterSpecificFormatFeatures = 0x00030002,
	WGPUNativeFeature_MultiDrawIndirectCount = 0x00030004,
	WGPUNativeFeature_VertexWritableStorage = 0x00030005,
	WGPUNativeFeature_TextureBindingArray = 0x00030006,
	WGPUNativeFeature_SampledTextureAndStorageBufferArrayNonUniformIndexing = 0x00030007,
	WGPUNativeFeature_PipelineStatisticsQuery = 0x00030008,
	WGPUNativeFeature_StorageResourceBindingArray = 0x00030009,
	WGPUNativeFeature_PartiallyBoundBindingArray = 0x0003000A,
	WGPUNativeFeature_TextureFormat16bitNorm = 0x0003000B,
	WGPUNativeFeature_TextureCompressionAstcHdr = 0x0003000C,
	WGPUNativeFeature_MappablePrimaryBuffers = 0x0003000E,
	WGPUNativeFeature_BufferBindingArray = 0x0003000F,
	WGPUNativeFeature_StorageTextureArrayNonUniformIndexing = 0x00030010,
	WGPUNativeFeature_AddressModeClampToZero = 0x00030011,
	WGPUNativeFeature_AddressModeClampToBorder = 0x00030012,
	WGPUNativeFeature_PolygonModeLine = 0x00030013,
	WGPUNativeFeature_PolygonModePoint = 0x00030014,
	WGPUNativeFeature_ConservativeRasterization = 0x00030015,
	WGPUNativeFeature_ClearTexture = 0x00030016,
	WGPUNativeFeature_Multiview = 0x00030018,
	WGPUNativeFeature_VertexAttribute64bit = 0x00030019,
	WGPUNativeFeature_TextureFormatNv12 = 0x0003001A,
	WGPUNativeFeature_RayQuery = 0x0003001C,
	WGPUNativeFeature_ShaderF64 = 0x0003001D,
	WGPUNativeFeature_ShaderI16 = 0x0003001E,
	WGPUNativeFeature_ShaderEarlyDepthTest = 0x00030020,
	WGPUNativeFeature_Subgroup = 0x00030021,
	WGPUNativeFeature_SubgroupVertex = 0x00030022,
	WGPUNativeFeature_SubgroupBarrier = 0x00030023,
	WGPUNativeFeature_TimestampQueryInsideEncoders = 0x00030024,
	WGPUNativeFeature_TimestampQueryInsidePasses = 0x00030025,
	WGPUNativeFeature_ShaderInt64 = 0x00030026,
	WGPUNativeFeature_ShaderFloat32Atomic = 0x00030027,
	WGPUNativeFeature_TextureAtomic = 0x00030028,
	WGPUNativeFeature_TextureFormatP010 = 0x00030029,
	WGPUNativeFeature_PipelineCache = 0x0003002B,
	WGPUNativeFeature_ShaderInt64AtomicMinMax = 0x0003002C,
	WGPUNativeFeature_ShaderInt64AtomicAllOps = 0x0003002D,
	WGPUNativeFeature_TextureInt64Atomic = 0x00030030,
	WGPUNativeFeature_ShaderBarycentrics = 0x00030037,
	WGPUNativeFeature_SelectiveMultiview = 0x00030038,
	WGPUNativeFeature_MultisampleArray = 0x0003003A,
	WGPUNativeFeature_CooperativeMatrix = 0x0003003B,
	WGPUNativeFeature_ShaderPerVertex = 0x0003003C,
	WGPUNativeFeature_ShaderDrawIndex = 0x0003003D,
	WGPUNativeFeature_AccelerationStructureBindingArray = 0x0003003E,
	WGPUNativeFeature_MemoryDecorationCoherent = 0x0003003F,
	WGPUNativeFeature_MemoryDecorationVolatile = 0x00030040,
	WGPUNativeFeature_Force32 = 0x7FFFFFFF
}

enum WGPULogLevel : int32
{
	WGPULogLevel_Off = 0x00000000,
	WGPULogLevel_Error = 0x00000001,
	WGPULogLevel_Warn = 0x00000002,
	WGPULogLevel_Info = 0x00000003,
	WGPULogLevel_Debug = 0x00000004,
	WGPULogLevel_Trace = 0x00000005,
	WGPULogLevel_Force32 = 0x7FFFFFFF
}

enum WGPUDx12Compiler : int32
{
	WGPUDx12Compiler_Undefined = 0x00000000,
	WGPUDx12Compiler_Fxc = 0x00000001,
	WGPUDx12Compiler_Dxc = 0x00000002,
	WGPUDx12Compiler_Force32 = 0x7FFFFFFF
}

enum WGPUGles3MinorVersion : int32
{
	WGPUGles3MinorVersion_Automatic = 0x00000000,
	WGPUGles3MinorVersion_Version0 = 0x00000001,
	WGPUGles3MinorVersion_Version1 = 0x00000002,
	WGPUGles3MinorVersion_Version2 = 0x00000003,
	WGPUGles3MinorVersion_Force32 = 0x7FFFFFFF
}

enum WGPUPipelineStatisticName : int32
{
	WGPUPipelineStatisticName_VertexShaderInvocations = 0x00000000,
	WGPUPipelineStatisticName_ClipperInvocations = 0x00000001,
	WGPUPipelineStatisticName_ClipperPrimitivesOut = 0x00000002,
	WGPUPipelineStatisticName_FragmentShaderInvocations = 0x00000003,
	WGPUPipelineStatisticName_ComputeShaderInvocations = 0x00000004,
	WGPUPipelineStatisticName_Force32 = 0x7FFFFFFF
}

enum WGPUNativeQueryType : int32
{
	WGPUNativeQueryType_PipelineStatistics = 0x00030000,
	WGPUNativeQueryType_Force32 = 0x7FFFFFFF
}

enum WGPUDxcMaxShaderModel : int32
{
	WGPUDxcMaxShaderModel_V6_0 = 0x00000000,
	WGPUDxcMaxShaderModel_V6_1 = 0x00000001,
	WGPUDxcMaxShaderModel_V6_2 = 0x00000002,
	WGPUDxcMaxShaderModel_V6_3 = 0x00000003,
	WGPUDxcMaxShaderModel_V6_4 = 0x00000004,
	WGPUDxcMaxShaderModel_V6_5 = 0x00000005,
	WGPUDxcMaxShaderModel_V6_6 = 0x00000006,
	WGPUDxcMaxShaderModel_V6_7 = 0x00000007,
	WGPUDxcMaxShaderModel_Force32 = 0x7FFFFFFF
}

enum WGPUGLFenceBehaviour : int32
{
	WGPUGLFenceBehaviour_Normal = 0x00000000,
	WGPUGLFenceBehaviour_AutoFinish = 0x00000001,
	WGPUGLFenceBehaviour_Force32 = 0x7FFFFFFF
}

enum WGPUDx12SwapchainKind : int32
{
	WGPUDx12SwapchainKind_Undefined = 0x00000000,
	WGPUDx12SwapchainKind_DxgiFromHwnd = 0x00000001,
	WGPUDx12SwapchainKind_DxgiFromVisual = 0x00000002,
	WGPUDx12SwapchainKind_Force32 = 0x7FFFFFFF
}

/**
 * Discriminant for @ref WGPUNativeDisplayHandle.
 *
 * Identifies which platform's display connection is stored in the tagged union.
 * Use @ref WGPUNativeDisplayHandleType_None (the default when zero-initialized) when
 * no display handle is needed. Platforms with no display connection data (Windows,
 * macOS, iOS, Android) should use @ref WGPUNativeDisplayHandleType_None.
 */
enum WGPUNativeDisplayHandleType : int32
{
	WGPUNativeDisplayHandleType_None = 0x00000000,
	WGPUNativeDisplayHandleType_Xlib = 0x00000001,
	WGPUNativeDisplayHandleType_Xcb = 0x00000002,
	WGPUNativeDisplayHandleType_Wayland = 0x00000003,
	WGPUNativeDisplayHandleType_Force32 = 0x7FFFFFFF
}

enum WGPUPolygonMode : int32
{
	WGPUPolygonMode_Fill = 0,
	WGPUPolygonMode_Line = 1,
	WGPUPolygonMode_Point = 2,
}

enum WGPUNativeTextureFormat : int32
{
	WGPUNativeTextureFormat_NV12 = 0x00030007,
	WGPUNativeTextureFormat_P010 = 0x00030008,
}

enum WGPUNativeAddressMode : int32
{
	WGPUNativeAddressMode_ClampToBorder = 0x00000004,
	WGPUNativeAddressMode_Force32 = 0x7FFFFFFF
}

enum WGPUSamplerBorderColor : int32
{
	WGPUSamplerBorderColor_Undefined = 0x00000000,
	WGPUSamplerBorderColor_TransparentBlack = 0x00000001,
	WGPUSamplerBorderColor_OpaqueBlack = 0x00000002,
	WGPUSamplerBorderColor_OpaqueWhite = 0x00000003,
	WGPUSamplerBorderColor_Zero = 0x00000004,
	WGPUSamplerBorderColor_Force32 = 0x7FFFFFFF
}

typealias WGPUInstanceBackend = WGPUFlags;
static
{
	public const WGPUInstanceBackend WGPUInstanceBackend_All = 0x00000000;
	public const WGPUInstanceBackend WGPUInstanceBackend_Vulkan = 1 << 0;
	public const WGPUInstanceBackend WGPUInstanceBackend_GL = 1 << 1;
	public const WGPUInstanceBackend WGPUInstanceBackend_Metal = 1 << 2;
	public const WGPUInstanceBackend WGPUInstanceBackend_DX12 = 1 << 3;
	public const WGPUInstanceBackend WGPUInstanceBackend_BrowserWebGPU = 1 << 5;
	public const WGPUInstanceBackend WGPUInstanceBackend_Primary = (1 << 0) | (1 << 2) | (1 << 3) | (1 << 5);
	public const WGPUInstanceBackend WGPUInstanceBackend_Secondary = (1 << 1);
	public const WGPUInstanceBackend WGPUInstanceBackend_Force32 = 0x7FFFFFFF;
}

typealias WGPUInstanceFlag = WGPUFlags;
static
{
	public const WGPUInstanceFlag WGPUInstanceFlag_Empty = 0x00000000;
	public const WGPUInstanceFlag WGPUInstanceFlag_Debug = 1 << 0;
	public const WGPUInstanceFlag WGPUInstanceFlag_Validation = 1 << 1;
	public const WGPUInstanceFlag WGPUInstanceFlag_DiscardHalLabels = 1 << 2;
	public const WGPUInstanceFlag WGPUInstanceFlag_AllowUnderlyingNoncompliantAdapter = 1 << 3;
	public const WGPUInstanceFlag WGPUInstanceFlag_GPUBasedValidation = 1 << 4;
	public const WGPUInstanceFlag WGPUInstanceFlag_ValidationIndirectCall = 1 << 5;
	public const WGPUInstanceFlag WGPUInstanceFlag_AutomaticTimestampNormalization = 1 << 6;
	public const WGPUInstanceFlag WGPUInstanceFlag_Default = 1 << 24;
	public const WGPUInstanceFlag WGPUInstanceFlag_Debugging = 1 << 25;
	public const WGPUInstanceFlag WGPUInstanceFlag_AdvancedDebugging = 1 << 26;
	public const WGPUInstanceFlag WGPUInstanceFlag_WithEnv = 1 << 27;
	public const WGPUInstanceFlag WGPUInstanceFlag_Force32 = 0x7FFFFFFF;
}

typealias WGPUShaderRuntimeChecks = WGPUFlags;
static
{
	public const WGPUShaderRuntimeChecks WGPUShaderRuntimeChecks_None = 0x0000000000000000;
	public const WGPUShaderRuntimeChecks WGPUShaderRuntimeChecks_BoundsChecks = 0x0000000000000001;
	public const WGPUShaderRuntimeChecks WGPUShaderRuntimeChecks_ForceLoopBounding = 0x0000000000000002;
	public const WGPUShaderRuntimeChecks WGPUShaderRuntimeChecks_RayQueryInitializationTracking = 0x0000000000000004;
	public const WGPUShaderRuntimeChecks WGPUShaderRuntimeChecks_TaskShaderDispatchTracking = 0x0000000000000008;
	public const WGPUShaderRuntimeChecks WGPUShaderRuntimeChecks_MeshShaderPrimitiveIndicesClamp = 0x0000000000000010;
}

typealias WGPULogCallback = function void(WGPULogLevel level, WGPUStringView message, void* userdata);

/**
 * Xlib display connection data for @ref WGPUNativeDisplayHandle.
 */
[CRepr] struct WGPUXlibDisplayHandle
{
	    /** Pointer to the X11 @c Display (i.e. @c Display*). Must not be NULL. */
	public void* display;
	    /** X11 screen number. */
	public int32 screen;
}

/**
 * XCB display connection data for @ref WGPUNativeDisplayHandle.
 */
[CRepr] struct WGPUXcbDisplayHandle
{
	    /** Pointer to the XCB connection (i.e. @c xcb_connection_t*). Must not be NULL. */
	public void* connection;
	    /** X11 screen number. */
	public int32 screen;
}

/**
 * Wayland display connection data for @ref WGPUNativeDisplayHandle.
 */
[CRepr] struct WGPUWaylandDisplayHandle
{
	    /** Pointer to the Wayland display (i.e. @c wl_display*). Must not be NULL. */
	public void* display;
}

/**
 * Platform display connection, passed as a field of @ref WGPUInstanceExtras.
 *
 * This is a tagged union. Set @c type to indicate which variant is active, then
 * populate the corresponding field in @c data. Zero-initialization yields
 * @ref WGPUNativeDisplayHandleType_None, meaning no display handle is provided.
 *
 * Currently required by the GLES backend when presenting on Wayland. Other
 * backends ignore this field. If the instance is created with a display handle,
 * all surfaces created from it must use the same display connection.
 */
[CRepr] struct WGPUNativeDisplayHandle
{
	public WGPUNativeDisplayHandleType type;
	[Union] public struct
	{
		public WGPUXlibDisplayHandle xlib;
		public WGPUXcbDisplayHandle xcb;
		public WGPUWaylandDisplayHandle wayland;
	} data;
}

[CRepr] struct WGPUInstanceExtras
{
	public WGPUChainedStruct chain;
	    /**
	     * Which backends to enable.
	     * Zero (@ref WGPUInstanceBackend_All) enables all backends.
	     */
	public WGPUInstanceBackend backends;
	    /**
	     * Flags controlling debug/validation behavior.
	     * See @ref WGPUInstanceFlag for available flags.
	     */
	public WGPUInstanceFlag flags;
	    /**
	     * Which DX12 shader compiler to use.
	     * See @ref WGPUDx12Compiler. Ignored on non-DX12 backends.
	     */
	public WGPUDx12Compiler dx12ShaderCompiler;
	    /**
	     * Which OpenGL ES 3 minor version to request.
	     * See @ref WGPUGles3MinorVersion. Ignored on non-GL backends.
	     */
	public WGPUGles3MinorVersion gles3MinorVersion;
	    /**
	     * Controls OpenGL fence synchronization behavior.
	     * See @ref WGPUGLFenceBehaviour. Ignored on non-GL backends.
	     */
	public WGPUGLFenceBehaviour glFenceBehaviour;
	    /**
	     * File system path to @c dxcompiler.dll for dynamic DXC loading.
	     * Only used when @c dx12ShaderCompiler is @ref WGPUDx12Compiler_Dxc.
	     * An empty/undefined string view means the DLL will be searched for
	     * on the system PATH.
	     */
	public WGPUStringView dxcPath;
	    /**
	     * Maximum HLSL shader model version that DXC should target.
	     * See @ref WGPUDxcMaxShaderModel. Only used with the DXC compiler.
	     */
	public WGPUDxcMaxShaderModel dxcMaxShaderModel;
	    /**
	     * Which DX12 presentation system (swapchain kind) to use.
	     * See @ref WGPUDx12SwapchainKind. Ignored on non-DX12 backends.
	     */
	public WGPUDx12SwapchainKind dx12PresentationSystem;
	public uint8* budgetForDeviceCreation;
	public uint8* budgetForDeviceLoss;
	    /**
	     * Platform display connection to associate with this instance.
	     * Zero-initialized yields @ref WGPUNativeDisplayHandleType_None (no handle).
	     */
	public WGPUNativeDisplayHandle displayHandle;
}

[CRepr] struct WGPUDeviceExtras
{
	public WGPUChainedStruct chain;
	    /**
	     * File system path for API trace output.
	     *
	     * When set to a non-empty path, wgpu will record all API calls to
	     * the given directory, which can later be replayed for debugging.
	     * An empty/undefined string view disables tracing.
	     */
	public WGPUStringView tracePath;
}

[CRepr] struct WGPUNativeLimits
{
	    /** This struct chain is used as mutable in some places and immutable in others. */
	public WGPUChainedStruct chain;
	    /**
	     * Maximum number of live non-sampler bindings.
	     *
	     * Default is 1,000,000. Only meaningful on D3D12.
	     *
	     * @b Warning: On integrated GPUs, large values can cause significant
	     * system RAM consumption.
	     */
	public uint32 maxNonSamplerBindings;
	    /**
	     * Maximum number of individual resources within binding arrays that can be accessed
	     * in a single shader stage. Applies to all types of bindings except samplers.
	     */
	public uint32 maxBindingArrayElementsPerShaderStage;
	    /**
	     * Maximum number of individual samplers within binding arrays that
	     * can be accessed in a single shader stage.
	     */
	public uint32 maxBindingArraySamplerElementsPerShaderStage;
	    /**
	     * The maximum number of views that can be used in multiview rendering.
	     */
	public uint32 maxMultiviewViewCount;
}

[CRepr] struct WGPUShaderDefine
{
	public WGPUStringView name;
	    /** The value of the preprocessor macro (e.g. @c "1"). */
	public WGPUStringView value;
}

[CRepr] struct WGPUShaderSourceGLSL
{
	public WGPUChainedStruct chain;
	    /** The shader stage this GLSL source targets. */
	public WGPUShaderStage stage;
	    /** GLSL source code. */
	public WGPUStringView code;
	    /** Number of entries in @c defines. */
	public uint32 defineCount;
	public WGPUShaderDefine* defines;
}

[CRepr] struct WGPUShaderModuleDescriptorSpirV
{
	public WGPUStringView label;
	    /** Number of 32-bit words in @c source. */
	public uint32 sourceSize;
	public uint32* source;
}

[CRepr] struct WGPURegistryReport
{
	public uint numAllocated;
	public uint numKeptFromUser;
	public uint numReleasedFromUser;
	public uint elementSize;
}

[CRepr] struct WGPUHubReport
{
	public WGPURegistryReport adapters;
	public WGPURegistryReport devices;
	public WGPURegistryReport queues;
	public WGPURegistryReport pipelineLayouts;
	public WGPURegistryReport shaderModules;
	public WGPURegistryReport bindGroupLayouts;
	public WGPURegistryReport bindGroups;
	public WGPURegistryReport commandBuffers;
	public WGPURegistryReport renderBundles;
	public WGPURegistryReport renderPipelines;
	public WGPURegistryReport computePipelines;
	public WGPURegistryReport pipelineCaches;
	public WGPURegistryReport querySets;
	public WGPURegistryReport buffers;
	public WGPURegistryReport textures;
	public WGPURegistryReport textureViews;
	public WGPURegistryReport samplers;
}

[CRepr] struct WGPUGlobalReport
{
	public WGPURegistryReport surfaces;
	    /** Statistics for all other resource types, grouped by backend hub. */
	public WGPUHubReport hub;
}

[CRepr] struct WGPUInstanceEnumerateAdapterOptions
{
	public WGPUChainedStruct* nextInChain;
	public WGPUInstanceBackend backends;
}

[CRepr] struct WGPUBindGroupEntryExtras
{
	public WGPUChainedStruct chain;
	public WGPUBuffer* buffers;
	public uint bufferCount;
	public WGPUSampler* samplers;
	public uint samplerCount;
	public WGPUTextureView* textureViews;
	public uint textureViewCount;
}

[CRepr] struct WGPUBindGroupLayoutEntryExtras
{
	public WGPUChainedStruct chain;
	    /**
	     * Number of resources in this binding array slot. Corresponds to the
	     * array size in the shader (e.g. @c binding_array<T, @c N>).
	     */
	public uint32 count;
}

[CRepr] struct WGPUQuerySetDescriptorExtras
{
	public WGPUChainedStruct chain;
	public WGPUPipelineStatisticName* pipelineStatistics;
	public uint pipelineStatisticCount;
}

[CRepr] struct WGPUSurfaceConfigurationExtras
{
	public WGPUChainedStruct chain;
	    /**
	     * Desired maximum number of frames in flight (i.e. the number of monitor
	     * refreshes between @c wgpuSurfaceGetCurrentTexture and presentation).
	     *
	     * - 1: Minimize latency (CPU and GPU cannot run in parallel).
	     * - 2: Balance between latency and throughput (the default).
	     * - 3+: Maximize throughput.
	     */
	public uint32 desiredMaximumFrameLatency;
}

/**
 * Chained in @ref WGPUSurfaceDescriptor to make a @ref WGPUSurface wrapping a WinUI [`SwapChainPanel`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.swapchainpanel).
 */
[CRepr] struct WGPUSurfaceSourceSwapChainPanel
{
	public WGPUChainedStruct chain;
	    /**
	     * A pointer to the [`ISwapChainPanelNative`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/microsoft.ui.xaml.media.dxinterop/nn-microsoft-ui-xaml-media-dxinterop-iswapchainpanelnative)
	     * interface of the SwapChainPanel that will be wrapped by the @ref WGPUSurface.
	     */
	public void* panelNative;
}

[CRepr] struct WGPUPrimitiveStateExtras
{
	public WGPUChainedStruct chain;
	    /**
	     * Controls the way each polygon is rasterized.
	     * See @ref WGPUPolygonMode. Defaults to @ref WGPUPolygonMode_Fill.
	     */
	public WGPUPolygonMode polygonMode;
	    /**
	     * If set to true, the primitives are rendered with conservative
	     * overestimation. Only valid when @c polygonMode is
	     * @ref WGPUPolygonMode_Fill.
	     * Requires @ref WGPUNativeFeature_ConservativeRasterization.
	     */
	public WGPUBool conservative;
}

[CRepr] struct WGPUImageSubresourceRange
{
	public WGPUTextureAspect aspect;
	public uint32 baseMipLevel;
	public uint32 mipLevelCount;
	public uint32 baseArrayLayer;
	public uint32 arrayLayerCount;
}

[CRepr] struct WGPUSamplerDescriptorExtras
{
	public WGPUChainedStruct chain;
	public WGPUSamplerBorderColor samplerBorderColor;
}

static
{
	[CLink] public static extern void wgpuGenerateReport(WGPUInstance instance, WGPUGlobalReport* report);
	[CLink] public static extern uint wgpuInstanceEnumerateAdapters(WGPUInstance instance, WGPUInstanceEnumerateAdapterOptions* options, WGPUAdapter* adapters);
	[CLink] public static extern WGPUSubmissionIndex wgpuQueueSubmitForIndex(WGPUQueue queue, uint commandCount, WGPUCommandBuffer* commands);
	[CLink] public static extern float wgpuQueueGetTimestampPeriod(WGPUQueue queue);
	[CLink] public static extern WGPUBool wgpuDevicePoll(WGPUDevice device, WGPUBool wait, WGPUSubmissionIndex* submissionIndex);
	[CLink] public static extern WGPUShaderModule wgpuDeviceCreateShaderModuleSpirV(WGPUDevice device, WGPUShaderModuleDescriptorSpirV* descriptor);
	[CLink] public static extern void wgpuSetLogCallback(WGPULogCallback callback, void* userdata);
	[CLink] public static extern void wgpuSetLogLevel(WGPULogLevel level);
	[CLink] public static extern uint32 wgpuGetVersion();
	[CLink] public static extern void* wgpuDeviceGetNativeMetalDevice(WGPUDevice device);
	[CLink] public static extern void* wgpuQueueGetNativeMetalCommandQueue(WGPUQueue queue);
	[CLink] public static extern void* wgpuTextureGetNativeMetalTexture(WGPUTexture texture);
	[CLink] public static extern void wgpuRenderPassEncoderMultiDrawIndirect(WGPURenderPassEncoder encoder, WGPUBuffer buffer, uint64 offset, uint32 count);
	[CLink] public static extern void wgpuRenderPassEncoderMultiDrawIndexedIndirect(WGPURenderPassEncoder encoder, WGPUBuffer buffer, uint64 offset, uint32 count);
	[CLink] public static extern void wgpuRenderPassEncoderMultiDrawIndirectCount(WGPURenderPassEncoder encoder, WGPUBuffer buffer, uint64 offset, WGPUBuffer count_buffer, uint64 count_buffer_offset, uint32 max_count);
	[CLink] public static extern void wgpuRenderPassEncoderMultiDrawIndexedIndirectCount(WGPURenderPassEncoder encoder, WGPUBuffer buffer, uint64 offset, WGPUBuffer count_buffer, uint64 count_buffer_offset, uint32 max_count);
	[CLink] public static extern void wgpuComputePassEncoderBeginPipelineStatisticsQuery(WGPUComputePassEncoder computePassEncoder, WGPUQuerySet querySet, uint32 queryIndex);
	[CLink] public static extern void wgpuComputePassEncoderEndPipelineStatisticsQuery(WGPUComputePassEncoder computePassEncoder);
	[CLink] public static extern void wgpuRenderPassEncoderBeginPipelineStatisticsQuery(WGPURenderPassEncoder renderPassEncoder, WGPUQuerySet querySet, uint32 queryIndex);
	[CLink] public static extern void wgpuRenderPassEncoderEndPipelineStatisticsQuery(WGPURenderPassEncoder renderPassEncoder);
	[CLink] public static extern void wgpuComputePassEncoderWriteTimestamp(WGPUComputePassEncoder computePassEncoder, WGPUQuerySet querySet, uint32 queryIndex);
	[CLink] public static extern void wgpuRenderPassEncoderWriteTimestamp(WGPURenderPassEncoder renderPassEncoder, WGPUQuerySet querySet, uint32 queryIndex);
	[CLink] public static extern WGPUBool wgpuDeviceStartGraphicsDebuggerCapture(WGPUDevice device);
	[CLink] public static extern void wgpuDeviceStopGraphicsDebuggerCapture(WGPUDevice device);
	[CLink] public static extern void wgpuCommandEncoderClearTexture(WGPUCommandEncoder commandEncoder, WGPUTexture texture, WGPUImageSubresourceRange* range);
	[CLink] public static extern WGPUShaderModule wgpuDeviceCreateShaderModuleTrusted(WGPUDevice device, WGPUShaderModuleDescriptor* descriptor, WGPUShaderRuntimeChecks runtimeChecks);
}
