FileVersion = 1

[Project]
Name = "Sedulous.Textures.Resources"
TargetType = "BeefLib"
StartupObject = "Sedulous.Textures.Resources.Program"

[Dependencies]
corlib = "*"
"Sedulous.Resources" = "*"
"Sedulous.Textures" = "*"
"Sedulous.Images" = "*"
"Sedulous.Images.Loading" = "*"
