FileVersion = 1

[Project]
Name = "Sedulous.Texture.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Texture.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Compression" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.VFS" = "*"
