FileVersion = 1

[Project]
Name = "Sedulous.Heightfield.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Heightfield.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Heightfield.Pipeline" = "*"
"Sedulous.Heightfield.Resource" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
