FileVersion = 1

[Project]
Name = "Sedulous.Engine.Integration"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Integration.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Script" = "*"
