FileVersion = 1

[Project]
Name = "TowerDefense.Core"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resources" = "*"
"Sedulous.Images" = "*"
"Sedulous.Images.Resources" = "*"
"Sedulous.Images.STB" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Resources" = "*"
"Sedulous.Models" = "*"
"Sedulous.Models.FBX" = "*"
"Sedulous.Textures" = "*"
"Sedulous.Textures.Resources" = "*"
"Sedulous.Geometry.Tooling" = "*"
"Sedulous.Geometry.Tooling.Resources" = "*"
"Sedulous.Renderer" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Messaging" = "*"
"Sedulous.Engine.App" = "*"
"Sedulous.Images.SDL" = "*"
"Sedulous.Messaging.Runtime" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.UI" = "*"
"Sedulous.Images.IO" = "*"
"Sedulous.Audio" = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Serialization.OpenDDL" = "*"
"Sedulous.Resources" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VFS.Disk" = "*"
