FileVersion = 1

[Project]
Name = "Sedulous.Content.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Content.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Xml.Serialization" = "*"
"Sedulous.Xml" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
