FileVersion = 1

[Project]
Name = "Sedulous.Physics.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Physics.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Physics.Pipeline" = "*"
