FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample004_Compute"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample004_Compute.Program"

[Dependencies]
corlib = "*"
