FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Tests"
TargetType = "BeefTest"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.Fonts.Baked" = "*"
"Sedulous.Fonts.Importer" = "*"
"Sedulous.Fonts.Resources" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Serialization" = "*"
"Sedulous.Serialization.OpenDDL" = "*"
"Sedulous.OpenDDL" = "*"
