FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Fonts.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
