FileVersion = 1

[Project]
Name = "Sedulous.Physics.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Physics.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Pipeline" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
