FileVersion = 1

[Project]
Name = "Sedulous.Pipeline.Registration.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Pipeline.Registration.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Pipeline.Registration" = "*"
