FileVersion = 1

[Project]
Name = "Sedulous.Navigation.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Navigation.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Navigation" = "*"
"Sedulous.Navigation.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
