FileVersion = 1

[Project]
Name = "Sedulous.Net.WebSocket"
TargetType = "BeefLib"
StartupObject = "Sedulous.Net.WebSocket.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Http" = "*"
