FileVersion = 1

[Project]
Name = "Sedulous.Editor.PropertyAnimation.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.PropertyAnimation.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Scene" = "*"
"Sedulous.PropertyAnimation" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.PropertyAnimation" = "*"
