FileVersion = 1

[Project]
Name = "Sedulous.RHI.TestSupport"
TargetType = "BeefLib"
StartupObject = "Sedulous.RHI.TestSupport.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
