FileVersion = 1

[Project]
Name = "Sedulous.Particles.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Particles.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Particles.Pipeline" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.VFS" = "*"
