FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample017_MultiQueue"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample017_MultiQueue.Program"

[Dependencies]
corlib = "*"
