FileVersion = 1

[Project]
Name = "Sedulous.Engine.Composition"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Composition.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Script" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Engine.Domain" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Engine.GameInstance" = "*"
"Sedulous.Engine.Input" = "*"
"Sedulous.Engine.Navigation" = "*"
"Sedulous.Engine.Net" = "*"
"Sedulous.Engine.Particles" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.Script" = "*"
"Sedulous.Engine.Script.Facades" = "*"
"Sedulous.Engine.Spline" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.Engine.UI.Script" = "*"
"Sedulous.Engine.Vegetation" = "*"
