FileVersion = 1

[Project]
Name = "Sedulous.Texture.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Texture.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.DDS" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Compression" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.VFS" = "*"
