FileVersion = 1

[Project]
Name = "Sedulous.VG.Backend.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.VG.Backend.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.TestSupport" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.WebGPU" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Coverage.Baker" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Fonts.TrueType" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
