FileVersion = 1

[Project]
Name = "Sedulous.Materials.PipelineCache"
TargetType = "BeefLib"
StartupObject = "Sedulous.Materials.PipelineCache.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Materials" = "*"
