FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.RHI" = "*", "Sedulous.RenderGraph" = "*", "Sedulous.Materials" = "*", "Sedulous.Shaders" = "*", "Sedulous.Profiler" = "*", "Sedulous.DebugFont" = "*"}

[Project]
Name = "Sedulous.Renderer"
TargetType = "BeefLib"
