FileVersion = 1

[Project]
Name = "Sedulous.Scene.Resource.Integration.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Scene.Resource.Integration.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Xml" = "*"
"Sedulous.Xml.Serialization" = "*"
