FileVersion = 1

[Project]
Name = "RenderGraphSandbox"
StartupObject = "RenderGraphSandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.RHI.DX12" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RenderGraph" = "*"
"SampleFramework" = "*"
