FileVersion = 1

[Project]
Name = "Sedulous.Fonts.DistanceField.Baker.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Fonts.DistanceField.Baker.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.DistanceField" = "*"
"Sedulous.Fonts.DistanceField.Baker" = "*"
"Sedulous.Fonts.TrueType" = "*"
