FileVersion = 1

[Project]
Name = "Sedulous.Engine.Audio"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Audio" = "*"
"Sedulous.Audio.SDL3" = "*"
"Sedulous.Audio.Resources" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Core.Mathematics" = "*"
