FileVersion = 1

[Project]
Name = "Sedulous.Engine.Audio"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Audio.Program"

[Dependencies]
corlib = "*"
"Sedulous.Audio" = "*"
"Sedulous.Core" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
