FileVersion = 1

[Project]
Name = "ModelViewer"
StartupObject = "Sedulous.Tools.ModelViewer.Program"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Jobs" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Logging" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Renderer" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Shell" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.UI.Viewport" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.Images" = "*"
"Sedulous.Images.Loading" = "*"
"Sedulous.Images.STB" = "*"
"Sedulous.Images.SDL" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resources" = "*"
"Sedulous.Geometry.Tooling" = "*"
"Sedulous.Geometry.Tooling.Resources" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Resources" = "*"
"Sedulous.Textures" = "*"
"Sedulous.Textures.Resources" = "*"
"Sedulous.Models" = "*"
"Sedulous.Models.GLTF" = "*"
"Sedulous.Models.FBX" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Animation.Resources" = "*"
"Sedulous.Serialization.OpenDDL" = "*"
