FileVersion = 1

[Project]
Name = "Sedulous.Engine.Navigation.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Navigation.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Navigation" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Navigation" = "*"
"Sedulous.Navigation.Resource" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.VFS" = "*"
