FileVersion = 1

[Project]
Name = "Sedulous.Texture.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Texture.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Texture" = "*"
