FileVersion = 1

[Project]
Name = "Sedulous.Engine.Render.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Render.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Render" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Geometry.Resource" = "*"
