FileVersion = 1

[Project]
Name = "Sedulous.Terrain.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Terrain.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Lod" = "*"
"Sedulous.Terrain" = "*"
