FileVersion = 1

[Project]
Name = "Sedulous.Editor.Terrain"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Terrain.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Render" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Heightfield.Resource" = "*"
"Sedulous.Heightfield.Pipeline" = "*"
"Sedulous.Terrain" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Terrain.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
"Sedulous.Editor.App" = "*"
"Sedulous.Editor.Preview" = "*"
