FileVersion = 1

[Project]
Name = "Sedulous.Net.Replication.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Net.Replication.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Net.Replication" = "*"
