FileVersion = 1

[Project]
Name = "Sedulous.Editor.Audio"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Audio.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Image" = "*"
"Sedulous.Audio" = "*"
"Sedulous.Audio.Pipeline" = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.VG" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
