FileVersion = 1

[Project]
Name = "Sedulous.Models.GLTF"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Models" = "*"
"Sedulous.Images" = "*"
cgltf-Beef = "*"
"Sedulous.Images.Loading" = "*"
