FileVersion = 1

[Project]
Name = "Sedulous.Engine.SceneSurface.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.SceneSurface.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.SceneSurface" = "*"
