FileVersion = 1

[Project]
Name = "Sedulous.Engine.SceneSurface.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.SceneSurface.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Script" = "*"
"Sedulous.Engine.Spline" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.Engine.SceneSurface" = "*"
