FileVersion = 1

[Project]
Name = "Sedulous.Terrain.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Terrain.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Heightfield.Resource" = "*"
"Sedulous.Terrain" = "*"
"Sedulous.Terrain.Resource" = "*"
