FileVersion = 1

[Project]
Name = "Sedulous.Engine.Script.Facades"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Script.Facades.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Audio" = "*"
"Sedulous.Input" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Render" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Script" = "*"
"Sedulous.Spline" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Engine.Audio" = "*"
"Sedulous.Engine.Particles" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Script" = "*"
"Sedulous.Engine.Spline" = "*"
