FileVersion = 1

[Project]
Name = "Sedulous.Audio.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Audio.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Audio" = "*"
"Sedulous.Audio.Pipeline" = "*"
"Sedulous.Audio.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
