FileVersion = 1

[Project]
Name = "Sedulous.Terrain"
TargetType = "BeefLib"
StartupObject = "Sedulous.Terrain.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Lod" = "*"
