FileVersion = 1

[Project]
Name = "Samples.ParticleFX"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.ParticleFX.Program"

[Dependencies]
corlib = "*"
"Samples.Common" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Engine.Particles" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Extensions.Imgui" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Particles.Pipeline" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.VFS" = "*"
