FileVersion = 1

[Project]
Name = "Sedulous.Editor.Navigation.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Navigation.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Engine.Navigation" = "*"
"Sedulous.Navigation" = "*"
"Sedulous.Navigation.Resource" = "*"
"Sedulous.Navigation.Pipeline" = "*"
"Sedulous.Editor.Navigation" = "*"
