FileVersion = 1

[Project]
Name = "Sedulous.Pipeline.Registration"
TargetType = "BeefLib"
StartupObject = "Sedulous.Pipeline.Registration.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Script" = "*"
"Sedulous.Script.AngelScript" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Gamekit" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Audio.Resource" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Heightfield.Resource" = "*"
"Sedulous.Image.Resource" = "*"
"Sedulous.Input.Resource" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Model.Resource" = "*"
"Sedulous.Navigation.Resource" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.PropertyAnimation.Resource" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Script.Resource" = "*"
"Sedulous.Shaders.Resource" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.Animation.Pipeline" = "*"
"Sedulous.Audio.Pipeline" = "*"
"Sedulous.Fonts.Pipeline" = "*"
"Sedulous.Geometry.Pipeline" = "*"
"Sedulous.Heightfield.Pipeline" = "*"
"Sedulous.Image.Pipeline" = "*"
"Sedulous.Input.Pipeline" = "*"
"Sedulous.Materials.Pipeline" = "*"
"Sedulous.ModelImporter" = "*"
"Sedulous.Navigation.Pipeline" = "*"
"Sedulous.Particles.Pipeline" = "*"
"Sedulous.Physics.Pipeline" = "*"
"Sedulous.Pipeline.Cook" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Pipeline.ScriptSurface" = "*"
"Sedulous.PropertyAnimation.Pipeline" = "*"
"Sedulous.Script.AngelScript.Pipeline" = "*"
"Sedulous.Script.Pipeline" = "*"
"Sedulous.Shaders.Pipeline" = "*"
"Sedulous.Terrain.Pipeline" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.UI.Pipeline" = "*"
