FileVersion = 1

[Project]
Name = "Sedulous.LegacyGUI.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.LegacyGUI.Tests.Program"
DefaultNamespace = "Sedulous.LegacyGUI.Tests"

[Dependencies]
corlib = "*"
"Sedulous.LegacyGUI" = "*"
