FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample026_DynamicOffsets"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample026_DynamicOffsets.Program"

[Dependencies]
corlib = "*"
