FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample019_BatchUpload"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample019_BatchUpload.Program"

[Dependencies]
corlib = "*"
