FileVersion = 1

[Project]
Name = "Sedulous.Fonts.TrueType"
TargetType = "BeefLib"
StartupObject = "Sedulous.Fonts.TrueType.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Coverage" = "*"
"Sedulous.Image" = "*"
"Sedulous.VFS" = "*"
"stb_truetype-Beef" = "*"
