FileVersion = 1

[Project]
Name = "Sedulous.VFS.Pak.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.VFS.Pak.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VFS.Pak" = "*"
