FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Validation" = "*", "Sedulous.RHI.DX12" = "*", "Sedulous.RHI.Vulkan" = "*", GraphicsFramework = "*"}

[Project]
Name = "Sample030_RenderBundles"
StartupObject = "Sample030_RenderBundles.Program"
