FileVersion = 1

[Project]
Name = "Sedulous.Mcp.Http"
TargetType = "BeefLib"
StartupObject = "Sedulous.Mcp.Http.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Http" = "*"
"Sedulous.Json" = "*"
"Sedulous.Mcp" = "*"
