FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Fonts.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Coverage" = "*"
"Sedulous.Fonts.Coverage.Baker" = "*"
"Sedulous.Fonts.DistanceField" = "*"
"Sedulous.Fonts.DistanceField.Baker" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Fonts.TrueType" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.VFS" = "*"
