FileVersion = 1

[Project]
Name = "Sedulous.GUI.Runtime"

[Dependencies]
corlib = "*"
"Sedulous.GUI" = "*"
"Sedulous.GUI.Shell" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Images" = "*"
"Sedulous.Profiler" = "*"
corlib = "*"
