FileVersion = 1

[Project]
Name = "Sedulous.Fonts.DistanceField.Baker"
TargetType = "BeefLib"
StartupObject = "Sedulous.Fonts.DistanceField.Baker.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.DistanceField" = "*"
"Sedulous.Fonts.TrueType" = "*"
"msdfgen-Beef" = "*"
"stb_truetype-Beef" = "*"
