FileVersion = 1

[Project]
Name = "Sedulous.Image.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Image.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Image" = "*"
