FileVersion = 1

[Project]
Name = "Sedulous.Navigation.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Navigation.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Navigation" = "*"
"Sedulous.Navigation.Pipeline" = "*"
"Sedulous.Navigation.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
