FileVersion = 1

[Project]
Name = "Sedulous.UI.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Gamekit" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.VFS" = "*"
