FileVersion = 1

[Project]
Name = "Sedulous.Engine.Physics.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Physics.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Physics" = "*"
