FileVersion = 1

[Project]
Name = "Sedulous.Engine.Physics.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Physics.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.VFS" = "*"
