FileVersion = 1

[Project]
Name = "Sedulous.UI.Runtime"

[Dependencies]
corlib = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Platform" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Platform" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Images" = "*"
"Sedulous.Profiler" = "*"
corlib = "*"
