FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Runtime" = "*", "Sedulous.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.UI" = "*", "Sedulous.UI.Shell" = "*", "Sedulous.VG" = "*", "Sedulous.VG.Renderer" = "*", "Sedulous.RHI" = "*", "Sedulous.Shell" = "*", "Sedulous.Shaders" = "*", "Sedulous.Fonts" = "*", "Sedulous.Fonts.TTF" = "*", "Sedulous.Images" = "*", "Sedulous.Profiler" = "*"}

[Project]
Name = "Sedulous.UI.Runtime"
TargetType = "BeefLib"
