FileVersion = 1

[Project]
Name = "Sedulous.Net.Manager.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Net.Manager.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Net.Replication" = "*"
"Sedulous.Net.WebSocket" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Net.Manager" = "*"
