FileVersion = 1

[Project]
Name = "Sedulous.LegacyGUI.Runtime"
DefaultNamespace = "Sedulous.LegacyGUI.Runtime"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Core" = "*"
"Sedulous.LegacyGUI" = "*"
"Sedulous.LegacyGUI.Shell" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Drawing.Renderer" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Fonts.TTF" = "*"
