FileVersion = 1

[Project]
Name = "Sedulous.Extensions.Imgui"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"cimgui-Beef" = "*"
"Sedulous.Core" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Shell" = "*"
"Sedulous.VFS" = "*"
