FileVersion = 1

[Project]
Name = "Sedulous.Geometry.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Geometry.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Lod" = "*"
"Sedulous.Pipeline.Core" = "*"
"meshoptimizer-Beef" = "*"
