FileVersion = 1

[Project]
Name = "Sedulous.VG.Renderer"
TargetType = "BeefLib"
StartupObject = "Sedulous.VG.Renderer.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Image" = "*"
"Sedulous.Texture" = "*"
"Sedulous.VG" = "*"
