FileVersion = 1

[Project]
Name = "Sedulous.VG.Renderer"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.VG" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Images" = "*"
"Sedulous.Textures" = "*"
