FileVersion = 1

[Project]
Name = "Sedulous.Editor.ViewportTools"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.ViewportTools.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Render" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Editor.Core" = "*"
