FileVersion = 1

[Project]
Name = "Sedulous.Editor.Generic"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Generic.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
