FileVersion = 1

[Project]
Name = "EngineAnimationSandbox"
StartupObject = "EngineAnimationSandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.App" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.Engine.Core" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Renderer" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resources" = "*"
"Sedulous.Geometry.Tooling" = "*"
"Sedulous.Geometry.Tooling.Resources" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Textures.Resources" = "*"
"Sedulous.Images.IO" = "*"
"Sedulous.Images.STB" = "*"
"Sedulous.Images.SDL" = "*"
"Sedulous.Models" = "*"
"Sedulous.Models.GLTF" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Animation.Resources" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.UI" = "*"
"Sedulous.Shell" = "*"
