FileVersion = 1

[Project]
Name = "Sedulous.ModelImporter.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.ModelImporter.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Animation" = "*"
"Sedulous.Animation.Pipeline" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Pipeline" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Pipeline" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.DDS" = "*"
"Sedulous.Model" = "*"
"Sedulous.Model.Resource" = "*"
"Sedulous.ModelImporter" = "*"
"Sedulous.Physics.Pipeline" = "*"
"Sedulous.Pipeline.Cook" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.VFS" = "*"
