FileVersion = 1

[Project]
Name = "VGSandbox"
StartupObject = "VGSandbox.Program"

[Dependencies]
corlib = "*"
RuntimeSampleFramework = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.SVG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Images" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
