FileVersion = 1

[Project]
Name = "VGSandbox"
StartupObject = "VGSandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.SVG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.Images" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.VFS" = "*"
"Sedulous.VFS.Disk" = "*"
