FileVersion = 1

[Project]
Name = "Samples.PhysicsPlayground"
TargetType = "BeefConsoleApplication"
StartupObject = "Samples.PhysicsPlayground.Program"

[Dependencies]
corlib = "*"
"Samples.Common" = "*"
"Sedulous.Core" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Scene" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.Extensions.Imgui" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Graphics.Gpu" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Physics.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.SDL3" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Resource" = "*"
