FileVersion = 1

[Project]
Name = "Sedulous.Scripting.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Scripting.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scripting" = "*"
"Sedulous.Scripting.Fixture" = "*"
"Sedulous.Scripting.Null" = "*"
