FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample007_Instancing"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample007_Instancing.Program"

[Dependencies]
corlib = "*"
