FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample003_UniformBuffers"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample003_UniformBuffers.Program"

[Dependencies]
corlib = "*"
