FileVersion = 1

[Project]
Name = "Sedulous.VG.Renderer.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.VG.Renderer.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Image" = "*"
"Sedulous.Texture" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
