FileVersion = 1

[Project]
Name = "Sedulous.Pipeline.Cook.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Pipeline.Cook.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Pipeline.Cook" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.VFS" = "*"
