FileVersion = 1

[Project]
Name = "Sedulous.Editor.Scene.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Scene.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Editor.Scene" = "*"
