FileVersion = 1

[Project]
Name = "Sedulous.Editor.Scene.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Scene.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Settings" = "*"
"Sedulous.Xml" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Render" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Engine.Physics" = "*"
"Sedulous.Engine.Navigation" = "*"
"Sedulous.Engine.Animation" = "*"
"Sedulous.Engine.Script" = "*"
"Sedulous.Script.Resource" = "*"
"Sedulous.Editor.App" = "*"
"Sedulous.Model.Resource" = "*"
"Sedulous.ModelImporter" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Materials.Pipeline" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Animation.Pipeline" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Particles.Pipeline" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Engine.Project" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
"Sedulous.Editor.Scene" = "*"
