FileVersion = 1

[Project]
Name = "Sedulous.Render.Backend.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Render.Backend.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.PipelineCache" = "*"
"Sedulous.Render" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.RenderGraph" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.TestSupport" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
