FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample023_CubeMap"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample023_CubeMap.Program"

[Dependencies]
corlib = "*"
