FileVersion = 1

[Project]
Name = "Sedulous.Editor.Generic.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Generic.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Editor.Generic" = "*"
