FileVersion = 1

[Project]
Name = "Sedulous.Net.Replication"
TargetType = "BeefLib"
StartupObject = "Sedulous.Net.Replication.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Scene" = "*"
