FileVersion = 1

[Project]
Name = "Sedulous.VG"
TargetType = "BeefLib"
StartupObject = "Sedulous.VG.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Fonts" = "*"
