FileVersion = 1

[Project]
Name = "Sedulous.ModelImporter"
TargetType = "BeefLib"
StartupObject = "Sedulous.ModelImporter.Program"

[Dependencies]
corlib = "*"
"Sedulous.Animation" = "*"
"Sedulous.Animation.Pipeline" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Pipeline" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.Pipeline" = "*"
"Sedulous.Materials.Resource" = "*"
"Sedulous.Model" = "*"
"Sedulous.Model.FBX" = "*"
"Sedulous.Model.GLTF" = "*"
"Sedulous.Model.IO" = "*"
"Sedulous.Model.Resource" = "*"
"Sedulous.Physics.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.VFS" = "*"
