FileVersion = 1

[Project]
Name = "Sedulous.Shaders.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Shaders.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
