FileVersion = 1

[Project]
Name = "Sedulous.Editor.App"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.App.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Xml.Serialization" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Image" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TrueType" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Fonts.DistanceField" = "*"
"Sedulous.Fonts.DistanceField.Baker" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.UI.Runtime" = "*"
"Sedulous.UI.Application" = "*"
"Sedulous.UI.Resource" = "*"
"Sedulous.Engine.UI" = "*"
"Sedulous.Input" = "*"
"Sedulous.Engine.Input" = "*"
"Sedulous.Settings" = "*"
"Sedulous.Engine.Project" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
"Sedulous.Editor.Preview" = "*"
