FileVersion = 1

[Project]
Name = "Sedulous.Editor.App"
StartupObject = "Sedulous.Editor.App.Program"

[Dependencies]
corlib = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Platform.SDL3" = "*"
"Sedulous.Editor" = "*"
