FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample028_ProceduralRT"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample028_ProceduralRT.Program"

[Dependencies]
corlib = "*"
