FileVersion = 1

[Project]
Name = "Sedulous.Editor.App.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.App.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Settings" = "*"
"Sedulous.Xml.Serialization" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TrueType" = "*"
"Sedulous.Fonts.DistanceField" = "*"
"Sedulous.Fonts.DistanceField.Baker" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Editor.App" = "*"
