FileVersion = 1

[Project]
Name = "Sedulous.Engine.Input"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Input.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Input" = "*"
