FileVersion = 1

[Project]
Name = "Sedulous.Editor.Texture"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Texture.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Texture" = "*"
"Sedulous.Texture.Compression" = "*"
"Sedulous.Texture.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
