FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample027_3DTexture"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample027_3DTexture.Program"

[Dependencies]
corlib = "*"
