FileVersion = 1

[Project]
Name = "Sedulous.Scene.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Scene.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Scene.Resource" = "*"
