FileVersion = 1

[Project]
Name = "Sedulous.Animation.Resource"
TargetType = "BeefLib"
StartupObject = "Sedulous.Animation.Resource.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Animation" = "*"
