FileVersion = 1

[Project]
Name = "Sedulous.Engine.Particles.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Particles.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Particles" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.VFS" = "*"
