FileVersion = 1

[Project]
Name = "Sedulous.Model.Resource.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Model.Resource.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Content" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Animation" = "*"
"Sedulous.Animation.Resource" = "*"
"Sedulous.Model" = "*"
"Sedulous.Model.Resource" = "*"
