FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Serialization" = "*", "Sedulous.Serialization.OpenDDL" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "Sedulous.Engine.Core.Tests"
TargetType = "BeefTest"
