FileVersion = 1

[Project]
Name = "Sedulous.Image.DDS.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Image.DDS.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.DDS" = "*"
