FileVersion = 1

[Project]
Name = "SampleVG001_Shapes"
StartupObject = "SampleVG001_Shapes.Program"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.Validation" = "*"
GraphicsFramework = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.SVG" = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime.Graphics" = "*"
"Sedulous.Shell.SDL3" = "*"
