FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Fonts.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Pipeline" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Image" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.VFS" = "*"
