FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Fonts.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Fonts.Pipeline" = "*"
