FileVersion = 1

[Project]
Name = "Sedulous.Engine.Terrain.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.Terrain.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Core" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Render" = "*"
"Sedulous.Resource" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Scene.Resource" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Terrain" = "*"
"Sedulous.Terrain.Resource" = "*"
