FileVersion = 1

[Project]
Name = "Sedulous.Mcp.Http.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Mcp.Http.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Http" = "*"
"Sedulous.Json" = "*"
"Sedulous.Mcp" = "*"
"Sedulous.Mcp.Http" = "*"
