FileVersion = 1

[Project]
Name = "Sedulous.Integration.TextureCompression"
TargetType = "BeefTest"
StartupObject = "Sedulous.Integration.TextureCompression.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
"Sedulous.Materials.PipelineCache" = "*"
"Sedulous.Render" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.RenderGraph" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.DX12" = "*"
"Sedulous.RHI.TestSupport" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.WebGPU" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.System" = "*"
"Sedulous.Texture.Compression" = "*"
"Sedulous.VFS" = "*"
