FileVersion = 1

[Project]
Name = "Sedulous.Engine.DefaultApp.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Engine.DefaultApp.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Engine.DefaultApp" = "*"
"Sedulous.Fonts.Resource" = "*"
"Sedulous.Graphics" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Texture.Resource" = "*"
"Sedulous.VFS" = "*"
