FileVersion = 1

[Project]
Name = "Sedulous.Image.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Image.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Image.Pipeline" = "*"
