FileVersion = 1

[Project]
Name = "Sedulous.Audio.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Audio.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Audio" = "*"
"Sedulous.Audio.Resource" = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Pipeline.Importer" = "*"
"Sedulous.VFS" = "*"
