FileVersion = 1

[Project]
Name = "Sedulous.Script.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Script.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Script" = "*"
"Sedulous.Script.Fixture" = "*"
"Sedulous.Script.Null" = "*"
