FileVersion = 1

[Project]
Name = "Sedulous.Shaders.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Shaders.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Shaders.Resource" = "*"
"Sedulous.VFS" = "*"
