FileVersion = 1

[Project]
Name = "Sedulous.Net.WebSocket.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Net.WebSocket.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Net" = "*"
"Sedulous.Http" = "*"
"Sedulous.Net.WebSocket" = "*"
