FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample029_ResolveTexture"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample029_ResolveTexture.Program"

[Dependencies]
corlib = "*"
