FileVersion = 1

[Project]
Name = "Sedulous.Geometry.Pipeline.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Geometry.Pipeline.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Pipeline" = "*"
"Sedulous.Geometry.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Xml.Serialization" = "*"
