FileVersion = 1

[Project]
Name = "Sedulous.Runtime.Graphics"
TargetType = "BeefLib"
StartupObject = "Sedulous.RuntimeGraphics.Program"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.DX12" = "*"
"Sedulous.Platform" = "*"
