FileVersion = 1

[Project]
Name = "Sedulous.Render.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Render.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Render.Api" = "*"
"Sedulous.Render" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Materials" = "*"
