FileVersion = 1

[Project]
Name = "Sedulous.Editor.Heightfield"
TargetType = "BeefLib"
StartupObject = "Sedulous.Editor.Heightfield.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Content" = "*"
"Sedulous.Image" = "*"
"Sedulous.Image.IO" = "*"
"Sedulous.Heightfield.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.App" = "*"
