FileVersion = 1

[Project]
Name = "Sedulous.Editor.Vegetation.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Editor.Vegetation.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Scene" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Resource" = "*"
"Sedulous.Render" = "*"
"Sedulous.Heightfield" = "*"
"Sedulous.Terrain" = "*"
"Sedulous.Terrain.Resource" = "*"
"Sedulous.Vegetation" = "*"
"Sedulous.Vegetation.Resource" = "*"
"Sedulous.Vegetation.Pipeline" = "*"
"Sedulous.Pipeline.Core" = "*"
"Sedulous.Engine.Terrain" = "*"
"Sedulous.Engine.Vegetation" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Editor.Core" = "*"
"Sedulous.Editor.ViewportTools" = "*"
"Sedulous.Editor.App" = "*"
"Sedulous.Editor.Vegetation" = "*"
