FileVersion = 1

[Project]
Name = "Samples.Common"
TargetType = "BeefLib"
StartupObject = "Samples.Common.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.VFS" = "*"
"Sedulous.Shell" = "*"
