FileVersion = 1

[Project]
Name = "Sedulous.Graphics.Null"
TargetType = "BeefLib"
StartupObject = "Sedulous.Graphics.Null.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Null" = "*"
"Sedulous.Graphics" = "*"
