FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Importer"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.Baked" = "*"
"Sedulous.Fonts.TTF" = "*"
