FileVersion = 1

[Project]
Name = "astcenc-Beef"
TargetType = "BeefLib"
StartupObject = "astcenc_Beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/astcenc.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/astcenc.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/astcenc.lib"]

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)/dist/Release-Linux64/libastcenc.a"]

[Configs.Release.Linux64]
LibPaths = ["$(ProjectDir)/dist/Release-Linux64/libastcenc.a"]

[Configs.Test.Linux64]
LibPaths = ["$(ProjectDir)/dist/Release-Linux64/libastcenc.a"]
