FileVersion = 1

[Project]
Name = "Sedulous.Particles.Pipeline"
TargetType = "BeefLib"
StartupObject = "Sedulous.Particles.Pipeline.Program"

[Dependencies]
corlib = "*"
"Sedulous.Content" = "*"
"Sedulous.Core" = "*"
"Sedulous.Particles" = "*"
"Sedulous.Particles.Resource" = "*"
"Sedulous.Pipeline.Core" = "*"
