FileVersion = 1

[Project]
Name = "Sedulous.Samples.RHI.Sample005_BindGroups"
TargetType = "BeefGUIApplication"
StartupObject = "Sedulous.Samples.RHI.Sample005_BindGroups.Program"

[Dependencies]
corlib = "*"
